### DISCUSSION TITLE
Feature request: Mixins for choosing font types

### DISCUSSION THREAD

**Discussion by lonix1** [FortAwesome/Font-Awesome#20924] [Feature Requests]
**Is your feature request related to a problem? Please describe.**
In many modern systems, only the woff/woff2 typefaces are used. Other packages (e.g. fontsource) don't include the other typefaces at all. Those other ones just bloat our output bundles for no benefit.

When importing the scss (e.g. in webpack), we need to cater for all the fontfaces as they are all included in fontawesome's scss.

**Describe the solution you'd like**
Instead of including all of them, export a mixin that allows us to opt-in to the ones we want.

**Describe alternatives you've considered**
An easy alternative is to write the mixin ourselves. But that defeats the point in a bundler - you want to point it to the fontawesome library and let it do it's magic.

**Additional context**
Here is a simple implementation, to give you an idea. All the combinations would need to be provided.

For example, this is from `solid.scss`:
````scss
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 900;
  font-display: $fa-font-display;
  src: url('#{$fa-font-path}/fa-solid-900.eot');
  src: url('#{$fa-font-path}/fa-solid-900.eot?#iefix') format('embedded-opentype'),
       url('#{$fa-font-path}/fa-solid-900.woff2') format('woff2'),
       url('#{$fa-font-path}/fa-solid-900.woff') format('woff'),
       url('#{$fa-font-path}/fa-solid-900.ttf') format('truetype'),
       url('#{$fa-font-path}/fa-solid-900.svg#fontawesome') format('svg');
}
````

So all the variants are included in output bundles.

Rather provide a mixin like this:
````scss
$eot:   true !default;
$woff:  true !default;
$woff2: true !default;
$ttf:   true !default;
$svg:   true !default;

@mixin fontface(
  $eot:   $eot,
  $woff:  $woff,
  $woff2: $woff2,
  $ttf:   $ttf,
  $svg:   $svg
  ) {
  @font-face {
    font-family: 'Font Awesome 5 Free';
    font-style: normal;
    font-weight: 900;
    font-display: $fa-font-display;
    @if $eot and $woff and $woff2 and $ttf and $svg {      // ALL TYPES
      src: url('#{$fa-font-path}/fa-solid-900.eot');
      src: url('#{$fa-font-path}/fa-solid-900.eot?#iefix') format('embedded-opentype'),
           url('#{$fa-font-path}/fa-solid-900.woff2') format('woff2'),
           url('#{$fa-font-path}/fa-solid-900.woff') format('woff'),
           url('#{$fa-font-path}/fa-solid-900.ttf') format('truetype'),
           url('#{$fa-font-path}/fa-solid-900.svg#fontawesome') format('svg');
    }
    @if $eot and not ($woff and $woff2 and $ttf and $svg) {   // ONLY eot
      src: ...
    }
    @else if $eot and not ($woff and $woff2 and $ttf) and $svg {  // ONLY eot and svg
      src: ...
    }
    // else...
    // else...
    // else...
  }
}
````

**Feature request checklist**
- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> In many modern systems, only the woff/woff2 typefaces are used. Other packages (e.g. fontsource) don't include the other typefaces at all. Those other ones just bloat our output bundles for no benefit.

FA6 will drop legacy formats. FA6 will include by default `woff`, `woff2`, and `ttf`. At the moment, it is not yet decided wether to include the `ttf` in the `@font-face` definition or not.

Maybe we can use this approach to conditionally include `ttf`

> All the combinations would need to be provided.

I would avoid such a mixin, it will end up with `5^2` conditional branches

> An easy alternative is to write the mixin ourselves. But that defeats the point in a bundler - you want to point it to the fontawesome library and let it do it's magic.

I think the best approach is to import `fontawesome.scss` and provide custom `${style}.scss`, according to specific needs. That will not require to write and maintain a complex mixin and is flexible enough with negligible effort on developer's side

@robmadole any thoughts?

**Comment by lonix1** [comment]
That is good news... if FA6 will only includes three file types, then the mixin becomes really simple!

Only 7 combinations:

````scss
     if !woff and !woff2 and  ttf
else if !woff and  woff2 and !ttf
else if !woff and  woff2 and  ttf
else if  woff and !woff2 and !ttf
else if  woff and !woff2 and  ttf
else if  woff and  woff2 and !ttf
else if  woff and  woff2 and  ttf
````

**Comment by lonix1** [comment]
This is a good idea, let me show you an example. For webpack and other tools too:

Instead of customizing it like this:
````scss
// set source path
$fa-font-path: '@fortawesome/fontawesome-free/webfonts';
// extracted from fontawesome.scss
@import '@fortawesome/fontawesome-free/scss/fontawesome';
// regular.scss
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  font-display: $fa-font-display;
  src: url('#{$fa-font-path}/fa-regular-400.woff2') format('woff2'),
       url('#{$fa-font-path}/fa-regular-400.woff') format('woff');
}
.far {
  font-family: 'Font Awesome 5 Free';
  font-weight: 400;
}
// extracted from solid.scss
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 900;
  font-display: $fa-font-display;
  src: url('#{$fa-font-path}/fa-solid-900.woff2') format('woff2'),
       url('#{$fa-font-path}/fa-solid-900.woff') format('woff');
}
.fa,
.fas {
  font-family: 'Font Awesome 5 Free';
  font-weight: 900;
}
// extracted from brands.scss
// ...
````

We can do this:
````js
$fa-font-path: '@fortawesome/fontawesome-free/webfonts';
@import '@fortawesome/fontawesome-free/scss/fontawesome';
@import '@fortawesome/fontawesome-free/scss/solid';
@import '@fortawesome/fontawesome-free/scss/regular';

@include fontfaceSolid  ($woff: true, $woff2: true, $ttf: false);
@include fontfaceRegular($woff: true, $woff2: true, $ttf: false);
````
