### DISCUSSION TITLE
Icon Request: fa-sort-date-asc & fa-sort-date-desc

### DISCUSSION THREAD

**Discussion by schettino72** [FortAwesome/Font-Awesome#21158] [Icon Requests]
Same style as `fa-sort-alpha`, `fa-sort-numeric`... but with a calendar beside the arrow.

**Comment by fschaeffer** [comment]
+1 would finish the sort-series ....

**Comment by pyornkrachzark** [comment]
Another +1 on this one. Tried stacking the sort and calendar-o icons to make something that works, but no luck there. Having some date sorting icons would be awesome!

**Comment by ghost** [comment]
+1

**Comment by scottselby** [comment]
over a year later .... I want this too!

**Comment by mkapteijns** [comment]
+1

**Comment by deseman** [comment]
+1

**Comment by cstoffer** [comment]
+1

**Comment by Timmer247** [comment]
+1

**Comment by MrBemd** [comment]
+1

**Comment by yzinkovets** [comment]
+1

**Comment by KyleMit** [comment]
You can roll your own by combining `.fa-long-arrow-down` with text representing month sort options, and then adjust their positioning to fit a single icon.


For example, the following HTML `<i class="fa fa-long-arrow-down"></i> `  works by adding this style:

```css
fa-long-arrow-down::before { content: "\f175"; }
```

In similar fashion, you could place an arrow along with extra text by leveraging the [`::after` pseudo element][1] like this:

```css
.fa-custom-sort-date-asc::before  { content: "\f175";  }
.fa-custom-sort-date-desc::before { content: "\f175";  }
.fa-custom-sort-date-asc::after   { content: "JAN DEC";}
.fa-custom-sort-date-desc::after  { content: "DEC JAN";}
```

After that, you just need to style the text with a fixed width so it wraps to a new line and move it around positionally and adjust the size in CSS.  Which will produce something like this:
![custom date icon](https://user-images.githubusercontent.com/4307307/39258272-97a5ce22-4881-11e8-8a21-ca65e1be4181.png)

For comparison to the A→Z or the 1→9 icons, here's the regular Font Awesome Icons compared to the custom implementation with just arrows and characters

![Stock vs. Custom](https://user-images.githubusercontent.com/4307307/39258503-1afee204-4882-11e8-97d9-243e292fba1d.png)

And here's the same thing zoomed in for a closer look:

![Stock vs. Custom Zoomed](https://user-images.githubusercontent.com/4307307/39258515-27121f2a-4882-11e8-89d0-bc3ac5074321.png)

## Here's a full [Demo in jsFiddle][2]

And here's the complete CSS styles (for consistency, I also added similar styles for the alphabetic and numeric characters to make sure they looked and behaved as similar as possible):

```css
.fa-custom-sort-date-asc,
.fa-custom-sort-date-desc{
  position: relative;
  width: 35px;
}

.fa-custom-sort-date-asc::before,
.fa-custom-sort-date-desc::before{
    content: "\f175";
    position: relative;
    right: 7px;
}

.fa-custom-sort-date-asc::after,
.fa-custom-sort-date-desc::after{
    position: absolute;
    width: 18px;
    top: 0px;
    right: 0px;
    font-size: 10px;
    line-height: 9px;
    font-family: "courier new",monospace;
    font-weight: bold;
}

.fa-custom-sort-date-asc::after { content: "JAN DEC";}
.fa-custom-sort-date-desc::after{ content: "DEC JAN";}

.fa-custom-sort-alpha-asc,
.fa-custom-sort-alpha-desc,
.fa-custom-sort-numeric-asc,
.fa-custom-sort-numeric-desc{
  position: relative;
}


.fa-custom-sort-alpha-asc::before,
.fa-custom-sort-alpha-desc::before,
.fa-custom-sort-numeric-asc::before,
.fa-custom-sort-numeric-desc::before{
    content: "\f175";
    position: relative;
    right: 5px;
}
.fa-custom-sort-alpha-asc::after,
.fa-custom-sort-alpha-desc::after,
.fa-custom-sort-numeric-asc::after,
.fa-custom-sort-numeric-desc::after{
    position: absolute;
    width: 13px;
    top: -1px;
    right: 1px;
    font-size: 11px;
    line-height: 9px;
    font-family: "courier new",monospace;
    font-weight: bold;
}

.fa-custom-sort-numeric-asc::after,
.fa-custom-sort-numeric-desc::after{
    font-family: monospace;
}


.fa-custom-sort-alpha-asc::after { content: "A Z";}
.fa-custom-sort-alpha-desc::after{ content: "Z A";}

.fa-custom-sort-numeric-asc::after { content: "1 9";}
.fa-custom-sort-numeric-desc::after{ content: "9 1";}
```

[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/::after
[2]: https://jsfiddle.net/KyleMit/u0m0ycfx/
