### ISSUE TITLE
rotate 45,135,225,315

### ISSUE THREAD

**Issue by hackout** [FortAwesome/Font-Awesome#10047]
.fa-rotate-45{
    -moz-transform:    rotate(45deg);
    -o-transform:      rotate(45deg);
    -webkit-transform: rotate(45deg);
    transform:         rotate(45deg);
    -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.7071067811865474, M12=-0.7071067811865477, M21=0.7071067811865477, M22=0.7071067811865474, SizingMethod='auto expand')";
    filter: progid:DXImageTransform.Microsoft.Matrix(
            M11=0.7071067811865474,
            M12=-0.7071067811865477,
            M21=0.7071067811865477,
            M22=0.7071067811865474,
            SizingMethod='auto expand');
    margin-left: -50%; 
    margin-top: -50%;
}
.fa-rotate-135{
    -moz-transform:    rotate(135deg);
    -o-transform:      rotate(135deg);
    -webkit-transform: rotate(135deg);
    transform:         rotate(135deg);
    -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=-0.7071067811865477, M12=-0.7071067811865475, M21=0.7071067811865475, M22=-0.7071067811865477, SizingMethod='auto expand')";
    filter: progid:DXImageTransform.Microsoft.Matrix(
        M11=-0.7071067811865477,
        M12=-0.7071067811865475,
        M21=0.7071067811865475,
        M22=-0.7071067811865477,
        SizingMethod='auto expand');
    margin-left: -50%; 
    margin-top: -50%;
}
.fa-rotate-225{
    -moz-transform:    rotate(225deg);
    -o-transform:      rotate(225deg);
    -webkit-transform: rotate(225deg);
    transform:         rotate(225deg);
    -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=-0.7071067811865475, M12=0.7071067811865476, M21=-0.7071067811865476, M22=-0.7071067811865475, SizingMethod='auto expand')";
    filter: progid:DXImageTransform.Microsoft.Matrix(
            M11=-0.7071067811865475,
            M12=0.7071067811865476,
            M21=-0.7071067811865476,
            M22=-0.7071067811865475,
            SizingMethod='auto expand');
    margin-left: -50%; 
    margin-top: -50%;
}
.fa-rotate-315{
    -moz-transform:    rotate(315deg);
    -o-transform:      rotate(315deg);
    -webkit-transform: rotate(315deg);
    transform:         rotate(315deg);
    -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.7071067811865476, M12=0.7071067811865475, M21=-0.7071067811865475, M22=0.7071067811865476, SizingMethod='auto expand')";
    filter: progid:DXImageTransform.Microsoft.Matrix(
            M11=0.7071067811865476,
            M12=0.7071067811865475,
            M21=-0.7071067811865475,
            M22=0.7071067811865476,
            SizingMethod='auto expand');
    margin-left: -50%; 
    margin-top: -50%;
}

**Comment by hackout** [comment]
take it , if u need

**Comment by ryankane** [comment]
You can make those blocks easier to read by wrapping them in triple-back-ticks (grave ticks) like so.

<pre>&grave;&grave;&grave;css

/* style-code */

&grave;&grave;&grave;
</pre>

```css
.fa-rotate-45 {
  -moz-transform: rotate(45deg);
  -o-transform: rotate(45deg);
  -webkit-transform: rotate(45deg);
  transform: rotate(45deg);
  -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.7071067811865474, M12=-0.7071067811865477, M21=0.7071067811865477, M22=0.7071067811865474, SizingMethod='auto expand')";
  filter: progid: DXImageTransform.Microsoft.Matrix( M11=0.7071067811865474, M12=-0.7071067811865477, M21=0.7071067811865477, M22=0.7071067811865474, SizingMethod='auto expand');
  margin-left: -50%;
  margin-top: -50%;
}
```
```css
.fa-rotate-135 {
  -moz-transform: rotate(135deg);
  -o-transform: rotate(135deg);
  -webkit-transform: rotate(135deg);
  transform: rotate(135deg);
  -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=-0.7071067811865477, M12=-0.7071067811865475, M21=0.7071067811865475, M22=-0.7071067811865477, SizingMethod='auto expand')";
  filter: progid: DXImageTransform.Microsoft.Matrix( M11=-0.7071067811865477, M12=-0.7071067811865475, M21=0.7071067811865475, M22=-0.7071067811865477, SizingMethod='auto expand');
  margin-left: -50%;
  margin-top: -50%;
}
```
```css
.fa-rotate-225 {
  -moz-transform: rotate(225deg);
  -o-transform: rotate(225deg);
  -webkit-transform: rotate(225deg);
  transform: rotate(225deg);
  -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=-0.7071067811865475, M12=0.7071067811865476, M21=-0.7071067811865476, M22=-0.7071067811865475, SizingMethod='auto expand')";
  filter: progid: DXImageTransform.Microsoft.Matrix( M11=-0.7071067811865475, M12=0.7071067811865476, M21=-0.7071067811865476, M22=-0.7071067811865475, SizingMethod='auto expand');
  margin-left: -50%;
  margin-top: -50%;
}
```
```css
.fa-rotate-315 {
  -moz-transform: rotate(315deg);
  -o-transform: rotate(315deg);
  -webkit-transform: rotate(315deg);
  transform: rotate(315deg);
  -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.7071067811865476, M12=0.7071067811865475, M21=-0.7071067811865475, M22=0.7071067811865476, SizingMethod='auto expand')";
  filter: progid: DXImageTransform.Microsoft.Matrix( M11=0.7071067811865476, M12=0.7071067811865475, M21=-0.7071067811865475, M22=0.7071067811865476, SizingMethod='auto expand');
  margin-left: -50%;
  margin-top: -50%;
}
```
