### ISSUE TITLE
Add the ability to fully configure a class names

### ISSUE THREAD

**Issue by dima117** [FortAwesome/Font-Awesome#10166]
Hi,

I need to use the FA in the projects that are being developed according to [BEM methodology](https://en.bem.info/methodology/quick-start/). I need the special assembly of the FA styles with the class names which comply with the BEM naming rules.

To some extent class names can be configured by by `fa-css-prefix` variable, but I can not configure the util class names (e g  animation classes, size classes etc).

Can you add additional variables for common part of the class name for each group?

For example:

```scss
$fa-size-prefix:       #{$fa-css-prefix}- !default;
...

// Icon Sizes
// -------------------------

/* makes the font 33% larger relative to the icon container */
.#{$fa-size-prefix}lg {
  font-size: (4em / 3);
  line-height: (3em / 4);
  vertical-align: -15%;
}
.#{$fa-size-prefix}2x { font-size: 2em; }
.#{$fa-size-prefix}3x { font-size: 3em; }
.#{$fa-size-prefix}4x { font-size: 4em; }
.#{$fa-size-prefix}5x { font-size: 5em; }
```
