### ISSUE TITLE
How to include only the CSS rules you need

### ISSUE THREAD

**Issue by atifmansoor** [FortAwesome/Font-Awesome#10451]
Hi, 
I'm a beginner to SASS, and I'm trying to reduce the amount of rules being compiled into my main CSS file.  What I basically want to do is specify in my SASS files only the rules I need. In my case, I'm only using one icon (the fa-google rule) and that's the one I wanted included in my compiled CSS.
I've read the Sass docs, but I saw nothing about only selecting the rules you want. How can I achieve this?

**Comment by tagliala** [comment]
> In my case, I'm only using one icon (the fa-google rule) and that's the one I wanted included in my compiled CSS.

Hi,

Keep in mind that if you need just one icon, you have your users to download the whole font in any case (size depend on browser).

Given so, I should advise you to consider an `.svg` based solution with png fallback for IE8 if you still need it.

Also, this question is not strictly related to font awesome and it is neither an issue nor a request, so you should consider stack overflow for support requests.

btw, you need :

1. The global `.fa` rule, and you have the [`.fa-icon` mixin](https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_mixins.scss#L4)
2. The `::before` content attribute for your specific icon

```scss
/* THIS WILL NOT WORK OUT OF THE BOX. */
/* Partial paths may change */
/* You also need the /fonts folder in a proper location */

@import "fa/variables"
@import "fa/mixins"

.icon-google {
  @include fa-icon;
  &:before { content: $fa-var-google; }
}
```

```html
<span class="icon-google"></span>
```

https://jsfiddle.net/tagliala/jv6kLgp9/

hope it helps
