### ISSUE TITLE
Icon Request: icon-applemusic

### ISSUE THREAD

**Issue by adhesiv** [FortAwesome/Font-Awesome#10500]
Would like to request a new icon for Apple Music.

This would be used to link out to playlists, songs, added to footers, product pages etc.

**Comment by ryankane** [comment]
You could simply combine a music note with an apple, square, or circle.

```html
<span class="fa-apple-music fa-stack">
  <i class="fa fa-apple fa-stack-2x"></i>
  <i class="fa fa-music fa-stack-1x"></i>
</span>

<span class="fa-apple-music fa-stack">
  <i class="fa fa-square fa-stack-2x"></i>
  <i class="fa fa-music fa-stack-1x"></i>
</span>

<span class="fa-apple-music-o fa-stack">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-music fa-stack-1x"></i>
</span>

<span class="fa-apple-music fa-stack">
  <i class="fa fa-circle fa-stack-2x"></i>
  <i class="fa fa-music fa-stack-1x"></i>
</span>

<span class="fa-apple-music-o fa-stack">
  <i class="fa fa-circle-thin fa-stack-2x"></i>
  <i class="fa fa-music fa-stack-1x"></i>
</span>
```

```css
.fa-apple-music .fa-music:before {
  content: '\266B';
}
.fa-apple-music .fa-music {
  color: #FFFFFF;
}
.fa-apple-music-o .fa-music {
  color: #000000;
  font-size: 0.75rem;
  line-height: 1.90rem;
}
```

![apple-music](https://cloud.githubusercontent.com/assets/1094151/21897338/4ef6f5c4-d8b7-11e6-9619-79ed5bba155f.png)


> [**➥ JSFiddle Demo**](https://jsfiddle.net/MrPolywhirl/m9q66Lfm/)
