### ISSUE TITLE
icon-spin doesn't work in links.

### ISSUE THREAD

**Issue by bryanhelmig** [FortAwesome/Font-Awesome#1060]
Looks like the rule:

``` css
a [class^="icon-"],
a [class*=" icon-"],
a [class^="icon-"]:before,
a [class*=" icon-"]:before {
  display: inline;
}
```

Kills the `display: inline-block;` required to enable animation.
