### ISSUE TITLE
Icon request: icon-file-chart-o (icon-report)

### ISSUE THREAD

**Issue by jeanfbrito** [FortAwesome/Font-Awesome#1076]
I want to use it in a menu for reports. All the reports will be avaible in that menu.
http://www.cdc.gov/metrics/images/report_icon.gif
http://www.large-icons.com/stock-icons/large-toolbar/report.jpg

**Comment by coryasilva** [comment]
+1 for @jeanfbrito version of report.  When I think of report these come to mind:  [Example 1](https://www.iconfinder.com/icons/274308/analytics_business_chart_diagram_document_earnings_file_finance_financial_graph_page_paper_pie_profit_report_sales_sheet_statistics_text_icon#size=512),  [Example 2](https://www.iconfinder.com/icons/274324/analytics_audit_bar_bars_chart_diagram_document_earnings_file_finance_financial_graph_page_paper_profit_report_sales_sheet_statistics_text_icon).

Though before we get icon happy maybe there is some clever css way to implement these document types.  What about a [Contract](https://www.iconfinder.com/icons/274299/agreed_agreement_contract_convention_deal_document_file_hands_handshake_investment_page_paper_partnership_sign_signed_text_treaty_icon#size=512), [Approval/Award](https://www.iconfinder.com/icons/274313/approved_certified_diploma_document_file_license_page_paper_quality_text_icon#size=512), or an [Invoice](https://www.iconfinder.com/icons/274303/cash_currency_document_dollar_ecommerce_file_finance_invoice_money_page_paper_payment_price_profit_sales_report_shopping_icon#size=512), etc.

**Comment by rdeslonde** [comment]
+1

**Comment by baalthazaar1** [comment]
+1

**Comment by james8aus** [comment]
+1

**Comment by SouleDesigns** [comment]
+1

**Comment by renatomoselli** [comment]
+1, thanks!

**Comment by iYalovoy** [comment]
+1

**Comment by gficher** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by JeroenCollier** [comment]
+1

**Comment by kevspadilla** [comment]
+1

**Comment by etcho** [comment]
+1

**Comment by pitus** [comment]
+1

**Comment by kitloong** [comment]
+1

**Comment by tagliala** [comment]
Another example from #6366
![](https://cloud.githubusercontent.com/assets/3767882/7603572/08032496-f94b-11e4-8aa7-f3ab45f230cc.png)

**Comment by hpvd** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by roooodcastro** [comment]
+1

**Comment by prettycode** [comment]
+1

**Comment by jesujcastillom** [comment]
+1

**Comment by HugCoder** [comment]
Over 3 years and this isn't implemented yet? Wow...
I would really like a report icon, thanks!

**Comment by toddmo** [comment]
+1

**Comment by DaveSenn** [comment]
+1

**Comment by jasoncastellano** [comment]
+1

**Comment by ptiswitz** [comment]
+1 :)

**Comment by ryankane** [comment]
Here's an [_**EXAMPLE**_](https://jsfiddle.net/MrPolywhirl/ojnhafoc/) using stacked icons:

![font](https://cloud.githubusercontent.com/assets/1094151/26001582/d4679dd4-36fa-11e7-831f-2a45e0738b1f.png)

```html
<h2>Custom</h2>
<span class="fa fa-stack fa-report jumbo">
  <i class="fa fa-file-o fa-stack-1x"></i>
  <i class="fa fa-photo fa-stack-1x"></i>
  <i class="fa fa-bars left fa-stack-1x"></i>
  <i class="fa fa-bars right fa-stack-1x"></i>
  <i class="fa fa-bar-chart fa-stack-1x"></i>
  <i class="fa fa-pie-chart fa-stack-1x"></i>
</span>

<h2>Basic</h2>
<i class="fa fa-file-o jumbo"></i>
<i class="fa fa-file jumbo"></i>
<i class="fa fa-file-text jumbo"></i>
<i class="fa fa-file-text-o jumbo"></i>

<h2>File</h2>
<i class="fa fa-file-pdf-o jumbo"></i>
<i class="fa fa-file-code-o jumbo"></i>
<i class="fa fa-file-archive-o jumbo"></i>
<i class="fa fa-file-zip-o jumbo"></i>

<h2>Document</h2>
<i class="fa fa-file-word-o jumbo"></i>
<i class="fa fa-file-powerpoint-o jumbo"></i>
<i class="fa fa-file-excel-o jumbo"></i>

<h2>Media</h2>
<i class="fa fa-file-audio-o jumbo"></i>
<i class="fa fa-file-sound-o jumbo"></i>
<i class="fa fa-file-video-o jumbo"></i>
<i class="fa fa-file-movie-o jumbo"></i>
<i class="fa fa-file-image-o jumbo"></i>
<i class="fa fa-file-photo-o jumbo"></i>
<i class="fa fa-file-picture-o jumbo"></i>
```

```css
body   {
  padding: 0.5em;
  background: #FFF;
}
h2 {
  margin-top: 0.4em;
  margin-bottom: 0.25em;
  font-size: 1.2em;
  font-weight: bolder;
  font-family: serif;
}
.fa.jumbo { font-size: 4em; }
.fa-report {
  width: 0.8699em;
  height: 1em;
  line-height: 1em;
  vertical-align: top;
}
.fa-report .fa-photo {
  font-size: 0.2em;
  top: -1.4em;
  left: -0.9em;
}
.fa-report .fa-bars.left {
  font-size: 0.3em;
  top: 0.1em;
  left: -0.6em;
}
.fa-report .fa-bars.right {
  font-size: 0.3em;
  top: 0.1em;
  left: 0.6em;
}
.fa-report .fa-pie-chart {
  font-size: 0.2em;
  top: 1.5em;
  left: 0.9em;
}
.fa-report .fa-bar-chart {
  font-size: 0.2em;
  top: 1.5em;
  left: -0.9em;
}
```

Copied from: #11056
