### ISSUE TITLE
Bulleted Lists as linklist

### ISSUE THREAD

**Issue by studio-one-ag** [FortAwesome/Font-Awesome#1077]
Is in a linklist a link around the content, a negative text-indent on the anchor-tag is required. Otherwise the icon has a wrong position. 
The value of the negative text-indent is twice the value of the class "ul.icons-ul"-text-indent.

``` html
<ul class="icons-ul">
  <li><a href="#"><i class="icon-li icon-ok"></i>Bulleted lists (like this one)</a></li>
  <li><a href="#"><i class="icon-li icon-ok"></i>Buttons</a></li>
</ul>
```

hack:

``` css
    ul.icons-ul > li > a {
        text-indent: -1.428571428571429em;
    }
```
