### ISSUE TITLE
Icon Request: icon-vertical-line

### ISSUE THREAD

**Issue by fekoh** [FortAwesome/Font-Awesome#10812]
To show the the amount of a product in an online shop it would be useful to have multiple icons that represent the stock.

Like:
|
|||||
|||||||||

Maybe it would be even enough to have one vertical line icon and repeat that icon as needed.

Regards
Felix

**Comment by ryankane** [comment]
Couldn't you just stick to Unicode vertical lines/bars?

|Character|Name|Value|
|-|-|-|
|\||[VERTICAL LINE](http://www.fileformat.info/info/unicode/char/7c/index.htm)|U+007C|
|❘|[LIGHT VERTICAL BAR](http://www.fileformat.info/info/unicode/char/2758/index.htm)|U+2758|
|❙|[MEDIUM VERTICAL BAR](http://www.fileformat.info/info/unicode/char/2759/index.htm)|U+2759|
|❚|[HEAVY VERTICAL BAR](http://www.fileformat.info/info/unicode/char/275a/index.htm)|U+275A|

# CSS

```css
.fa-vertical-line:after       { content: "\007C" };
.fa-vertical-bar-light:after  { content: "\2758" };
.fa-vertical-bar-medium:after { content: "\2759" };
.fa-vertical-bar-heavy:after  { content: "\275A" };
```
