### ISSUE TITLE
Icon Request: fa-halfbath

### ISSUE THREAD

**Issue by ehasicka** [FortAwesome/Font-Awesome#10955]
For real estate, just need a half bath to go with the full bath.  Simply take existing fa-bath icon and show left half of it.  That's all...thank you!

**Comment by ryankane** [comment]
You can isolate the side of the tub using the following method.

```html
<span class="fa-stack fa-bath-half fa-lg">
  <i class="fa fa-bath fa-2x"></i>
</span>
```

```css
.fa-bath-half {
  position: relative;
  overflow: hidden;
  margin-left: -0.5em;
}

.fa-bath-half .fa-bath:first-child {
  position: absolute;
  right: -1rem;
}
```

Demo: [JSFiddle](https://jsfiddle.net/MrPolywhirl/sxo7ob3d/)
