### ISSUE TITLE
plz provide icon for reports

### ISSUE THREAD

**Issue by vshekharjha** [FortAwesome/Font-Awesome#11056]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by ryankane** [comment]
Here's an [_**EXAMPLE**_](https://jsfiddle.net/MrPolywhirl/ojnhafoc/) using stacked icons:

![font](https://cloud.githubusercontent.com/assets/1094151/26001582/d4679dd4-36fa-11e7-831f-2a45e0738b1f.png)

```html
<h2>Custom</h2>
<span class="fa fa-stack fa-report jumbo">
  <i class="fa fa-file-o fa-stack-1x"></i>
  <i class="fa fa-photo fa-stack-1x"></i>
  <i class="fa fa-bars left fa-stack-1x"></i>
  <i class="fa fa-bars right fa-stack-1x"></i>
  <i class="fa fa-bar-chart fa-stack-1x"></i>
  <i class="fa fa-pie-chart fa-stack-1x"></i>
</span>

<h2>Basic</h2>
<i class="fa fa-file-o jumbo"></i>
<i class="fa fa-file jumbo"></i>
<i class="fa fa-file-text jumbo"></i>
<i class="fa fa-file-text-o jumbo"></i>

<h2>File</h2>
<i class="fa fa-file-pdf-o jumbo"></i>
<i class="fa fa-file-code-o jumbo"></i>
<i class="fa fa-file-archive-o jumbo"></i>
<i class="fa fa-file-zip-o jumbo"></i>

<h2>Document</h2>
<i class="fa fa-file-word-o jumbo"></i>
<i class="fa fa-file-powerpoint-o jumbo"></i>
<i class="fa fa-file-excel-o jumbo"></i>

<h2>Media</h2>
<i class="fa fa-file-audio-o jumbo"></i>
<i class="fa fa-file-sound-o jumbo"></i>
<i class="fa fa-file-video-o jumbo"></i>
<i class="fa fa-file-movie-o jumbo"></i>
<i class="fa fa-file-image-o jumbo"></i>
<i class="fa fa-file-photo-o jumbo"></i>
<i class="fa fa-file-picture-o jumbo"></i>
```

```css
body   {
  padding: 0.5em;
  background: #FFF;
}
h2 {
  margin-top: 0.4em;
  margin-bottom: 0.25em;
  font-size: 1.2em;
  font-weight: bolder;
  font-family: serif;
}
.fa.jumbo { font-size: 4em; }
.fa-report {
  width: 0.8699em;
  height: 1em;
  line-height: 1em;
  vertical-align: top;
}
.fa-report .fa-photo {
  font-size: 0.2em;
  top: -1.4em;
  left: -0.9em;
}
.fa-report .fa-bars.left {
  font-size: 0.3em;
  top: 0.1em;
  left: -0.6em;
}
.fa-report .fa-bars.right {
  font-size: 0.3em;
  top: 0.1em;
  left: 0.6em;
}
.fa-report .fa-pie-chart {
  font-size: 0.2em;
  top: 1.5em;
  left: 0.9em;
}
.fa-report .fa-bar-chart {
  font-size: 0.2em;
  top: 1.5em;
  left: -0.9em;
}
```
