### ISSUE TITLE
Proposed a changing with an introduction of .fa::before pseudo-class

### ISSUE THREAD

**Issue by leoyli** [FortAwesome/Font-Awesome#11670]
Hi,

I'm currently using Font Awesome 4.7.0.  I hope the maintaining team can consider the following change:

## **Proposed changing**
Current:
```css
.fa {
  (...)
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

Modified:
```css
.fa {
  (...)
}

.fa::before {
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

## **Reason**
I'm using it on \<a\> html tags.  And as you may know, those properties will also affect on my content which wrapped by the tag with `.fa` class; therefore, I have to overwrite with extra, unnecessary codes.

I know I can customize by using SCSS... however, I don't think Font Awesome should affect anything other than the icons.

Any thought?
