### ISSUE TITLE
How To Use FA SVG Icons in CSS

### ISSUE THREAD

**Issue by Joyrex** [FortAwesome/Font-Awesome#11922]
I am upgrading from FA 4.7.0 to FA 5.0.1, and I like not being bound by font files anymore - the SVG renders much better in my opinion.

However, in my conversion, I forgot that I have FA codepoints in my CSS that reference the FA font files. How would I use the FA 5 codepoints in the CSS _without_ using the font files anymore?

For example:
```
/* Sorting asc */

table.dataTable thead .sorting_asc:before {
    font-family: "FontAwesome";
    right: 0.5em;
    content: "\f0de";
    font-weight: normal;
    opacity: 1;
}

table.dataTable thead .sorting_asc:after {
    font-family: "FontAwesome";
    right: 0.5em;
    content: "\f0de";
    font-weight: normal;
    opacity: 1;
}
```

Any help/advice is appreciated!

**Comment by rhettl** [comment]
Bump

Same here. In most cases I use FA in HTML. I worked to install the SVG, but I cannot do the below:

```scss
a[target="_blank"]:after {
  @extend .fa;
  content : $fa-var-external-link;
  margin-left : 5px;
}
```

I switched to SCSS webfonts and all works with the below:

```scss
a[target="_blank"]:after {
  @extend .far;
  content : fa-content($fa-var-external-link);
  margin-left : 5px;
}
```

But now I don't seem to be able to layer. All examples I can find of layering use the SVG+JS.
If this constitutes a new issue, I'm sorry for accidentally doubling up.

Thanks for any help
