### ISSUE TITLE
FontAwesome5 - Firefox Pseudoelements Not Working

### ISSUE THREAD

**Issue by dgmarques** [FortAwesome/Font-Awesome#12058]
I'm using the SB-Admin2 template. It uses MetisMenu for the navigation menu and I'm facing a problem with FontAwesome 5. I am using pseudoelements for the menu to change the icon when it is open/closed.

This means I have font awesome configured for pseudo elements:
```HTML
<script>
    FontAwesomeConfig = {
        searchPseudoElements: true
    }
</script>
<script src="/assets/fontawesome-free-5.0.2/js/fontawesome-all.min.js"></script>
```

It works just fine on Google Chrome, however when I go to try it on firefox, this happens:
![image](https://user-images.githubusercontent.com/34550273/34683385-cd93fe78-f499-11e7-9dc0-93f12dc54fbc.png)

A snippet of the pseudoelement in use:
```HTML
<div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a>
                        <i class="fas fa-chart-line"></i>
                        <b>Status</b>
                        <span class="fa arrow"></span>
                    </a>

                    <ul class="nav nav-second-level">
                        <li>
                            <a href="/pages/index.html">Overview</a>
                        </li>

                        <li>
                            <a href="/pages/realtime.html">Realtime</a>
                        </li>
                    </ul>
                </li>
```

And the pseudoelement class:
```CSS
.sidebar .arrow {
  float: right;
}
.sidebar .arrow:before {
  display: none;
  font-family: "Font Awesome 5 Solid";
  content: "\f104";
}
.sidebar .active > a > .arrow:before {
  display: none;
  font-family: "Font Awesome 5 Solid";
  content: "\f107";
}
```

Any feedback on what might be going wrong would be greatly appreciated. Thank you for your time!
