### ISSUE TITLE
Icon Request: fa-arrow-ne / nw / se / sw  and fa-arrow-circle-ne / nw / se / sw

### ISSUE THREAD

**Issue by markedro** [FortAwesome/Font-Awesome#12152]
8 new icons requested - all of these are related to the existing directional icons to accompany the up / down / left / right arrow and arrow-circle icons. 

I plan to use these for mobile directional indicators for locations. If a list of places gets generated with distance/direction combos for each place relative to where you are at that moment, then having just the up / down / left / right arrows representing North/South/East/West aren't granular enough to represent each direction. You would also need to have the abilities to indicate when something is North-East / North-West / South/East / and South-West

Thanks for the great stuff!

**Comment by wcit** [comment]
Would appreciate this also

**Comment by drtritm** [comment]
I need it too

**Comment by koerig** [comment]
You can use the "transformation" function "rotate(_angle_)".
in your HTML code:
```HTML
<i class="fas fa-arrow-right northwest"></i>
<i class="fas fa-arrow-right northeast"></i>
<i class="fas fa-arrow-right southeast"></i>
<i class="fas fa-arrow-right southwest"></i>
```

in the CSS style file:
```CSS
.fa-arrow-right.northwest { transform: rotate(-135deg); }
.fa-arrow-right.northeast { transform: rotate(-45deg); }
.fa-arrow-right.southeast { transform: rotate(45deg); }
.fa-arrow-right.southwest { transform: rotate(135deg); }
```

If you need it only in one place you can of course do it right at the DOM element:
```HTML
<i class="fas fa-arrow-right" style="transform: rotate(45deg);"></i>
```

So there is no need for another arrow icon since you are totally flexible in using the existing once in any direction and angle you need.
Have fun!

**Comment by koerig** [comment]
An even more generic way.

```CSS
.fas.northwest, .far.northwest, .fal.northwest, .fad.northwest { transform: rotate(-135deg); }
.fas.northeast, .far.northeast, .fal.northeast, .fad.northeast  { transform: rotate(-45deg); }
.fas.southeast, .far.southeast, .fal.southeast, .fad.southeast  { transform: rotate(45deg); }
.fas.southwest, .far.southwest, .fal.southwest, .fad.southwest  { transform: rotate(135deg); }
```
That way you can use the classnames "northwest, northeast, southeast, southwest" for any other icon in any style (_fas - solid, far - regular, fal - light, fad - duotone_).
