### ISSUE TITLE
I only showed one small square

### ISSUE THREAD

**Issue by xiaoyueyue165** [FortAwesome/Font-Awesome#12272]
I think this project is great, ask me how to use it, the document did not understand?
````
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="./web-fonts-with-css/css/fontawesome.min.css">
  <link rel="stylesheet" href="./web-fonts-with-css/webfonts/fa-brands-400.ttf">
</head>

<body>
  <i class="fas fa-camera-retro"></i>

  <div style="font-size:3em; color:Tomato">
    <i class="fas fa-camera-retro"></i>
  </div>

  <i class="fas fa-camera-retro fa-xs"></i>
  <i class="fas fa-camera-retro fa-sm"></i>
  <i class="fas fa-camera-retro fa-lg"></i>
  <i class="fas fa-camera-retro fa-2x"></i>
  <i class="fas fa-camera-retro fa-3x"></i>
  <i class="fas fa-camera-retro fa-5x"></i>
  <i class="fas fa-camera-retro fa-7x"></i>
  <i class="fas fa-camera-retro fa-10x"></i>
</body>

</html>
````

I did this, but I can not show the effect.
Duplicate demand Demand arrangement or quotation, are you OK?

**Comment by xiaoyueyue165** [comment]
I use the cdn link can demonstrate the effect, how do you want to do the local configuration?

````
  <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
````
Local configuration seems wrong



````css
//  fontawesome.min.css
@font-face {
  font-family: "FontAwesome";
  src: url("./fa-brands-400.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
````
