### ISSUE TITLE
3 icons missing out of 6.

### ISSUE THREAD

**Issue by CosmikCarrot** [FortAwesome/Font-Awesome#13827]
### Describe the problem

3 icons are not showing in other browsers apart from Safari.
Other browsers are showing this - https://screencast.com/t/NN9S11HZ65v
View URL - https://www.cosmikcarrot.com/web-services/messenger-chatbot-marketing/

### What did you expect?

Should be like this - https://screencast.com/t/QtP4Rvrd0I

### What version and implementation are you using?

Version: 5
Browser and version: 
- [x] Web Fonts with CSS

### Reproducible test case

https://www.cosmikcarrot.com/web-services/messenger-chatbot-marketing/

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that there is a third party software that is preventing Font Awesome to work

```css
// Line 1152 of style.css
.fab-rocket .et-pb-icon::after {
    content: "\f135";
    font-family: "FontAwesome", "Font Awesome 5 Free", "Font Awesome 5 Brands" !important;
    color: #FFF;
    font-size: 70px;
}
```

Please fix the above or contact your plugin/theme developer

Hope it helps

Closing here
