### ISSUE TITLE
facebook, google and twitter icon not work

### ISSUE THREAD

**Issue by macagoraga** [FortAwesome/Font-Awesome#14047]
I have correctly load fontawesome and all icons work fine apart facebook, google and twitter.

This is example of icon fa-users that work fine:

![screenshot from 2018-10-02 08-49-57](https://user-images.githubusercontent.com/5359394/46333419-9bcda980-c620-11e8-9bdf-94c6edd6d2c8.png)

and on the same page this is for facebook, as you can see the css for fa-facebook:before is correctly loaded, but icon is not visibile:

![screenshot from 2018-10-02 08-50-18](https://user-images.githubusercontent.com/5359394/46333427-9ff9c700-c620-11e8-9654-5d65180a70fb.png)

Any idea what can be?

Thanks

**Comment by macagoraga** [comment]
Thanks for reply.

I have try also using fab, fa, icon, etc. but none work.

As you can see on screenshot, there is css code for fa-facebook and fa, fal and icon all this should work.

Since I added:

```scss

@import 'fontawesome-pro-5.3.1-web/scss/fontawesome';
@import 'variables';

@font-face {
  font-family: $icon-font-family;
  font-style: normal;
  font-weight: 300;
  src: url('#{$fa-font-path}/fa-#{$icon-font-style}.eot');
  src: url('#{$fa-font-path}/fa-#{$icon-font-style}.eot?#iefix') format('embedded-opentype'),
  url('#{$fa-font-path}/fa-#{$icon-font-style}.woff2') format('woff2'),
  url('#{$fa-font-path}/fa-#{$icon-font-style}.woff') format('woff'),
  url('#{$fa-font-path}/fa-#{$icon-font-style}.ttf') format('truetype'),
  url('#{$fa-font-path}/fa-#{$icon-font-style}.svg#fontawesome') format('svg');
}

.fa,
.fal,
.icon {
  font-family: $icon-font-family;
  font-weight: $icon-font-weight;

  &.icon-fw {
    width: 1.8em;
  }
}
```

See here live: http://atl.socialveo.co/login
