### ISSUE TITLE
why is the fa-themeco icon not showing the word pro in my menu

### ISSUE THREAD

**Issue by dvolatility** [FortAwesome/Font-Awesome#14545]
Anyone know why the word pro in my themeco icon isn't showing in my mobile menu? It works fine on my desktop menu. Any help would be appreciated. It's just a filled shape. I use Blogger.

This is my code: 
```
<ul>
<li><a href='https://www.distressedvolatility.com/p/market-and-economic-news.html' title='Market, Economic and Business News'><i class='far fa-newspaper fa-2x'/></a></li>
<li><a href=''><i class='fab fa-themeco fa-2x'/></a></li>
 <li><a href='https://www.distressedvolatility.com/p/distressed-volatility-market-terminal.html' title='Advanced Interactive Chart and Market Terminal'><i class='fas fa-chart-line fa-2x'/></a></li>
</ul>
```

![screenshot 2019-01-24 at 1 48 10 pm](https://user-images.githubusercontent.com/13017946/51701939-7eae5380-1fe0-11e9-9d49-a7b9c4ec8404.png)

See the mobile menu at https://distressedvolatility.com after clicking on the three bars at the top.

**Comment by tagliala** [comment]
Hi,

Your css is setting `font-weight: 700` to `.mobile-navigation` and it is taking precedence over Font Awesome's settings.

Please remove that property or reset proper font weights inside mobile navigation:

```css
.mobile-navigation .fab,
.mobile-navigation .far {
  font-weight: 400;
}

.mobile-navigation .fa,
.mobile-navigation .fas {
  font-weight: 900;
}

.mobile-navigation .fal {
  font-weight: 300;
}
```

Hope it helps
