### ISSUE TITLE
Sass tries to nest @font-face rule

### ISSUE THREAD

**Issue by pondermatic** [FortAwesome/Font-Awesome#14648]
### Describe the problem

I would like to nest the Font Awesome CSS styles within a class selector to avoid incompatibilities with other WordPress themes and plugins that use older versions of Font Awesome. Unfortunately, Sass tries to nest @font-face rules which CSS does not allow.

For example:
```scss
.plugin-name {
  @import "../fontawesome-free/scss/regular.scss";
}
```

### Expected output

```css
@font-face {
  font-family: "Font Awesome 5 Free";
  font-style: normal;
  font-weight: 900;
  font-display: auto;
  src: url("../webfonts/fa-solid-900.eot");
  src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"), url("../webfonts/fa-solid-900.woff") format("woff"), url("../webfonts/fa-solid-900.ttf") format("truetype"), url("../webfonts/fa-solid-900.svg#fontawesome") format("svg");
}
.plugin-name .fa,
.plugin-name .fas {
  font-family: "Font Awesome 5 Free";
  font-weight: 900;
}
```

### Actual output

```css
@font-face {
  .plugin-name {
    font-family: "Font Awesome 5 Free";
    font-style: normal;
    font-weight: 900;
    font-display: auto;
    src: url("../webfonts/fa-solid-900.eot");
    src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"), url("../webfonts/fa-solid-900.woff") format("woff"), url("../webfonts/fa-solid-900.ttf") format("truetype"), url("../webfonts/fa-solid-900.svg#fontawesome") format("svg");
  }
}
.plugin-name .fa,
.plugin-name .fas {
  font-family: "Font Awesome 5 Free";
  font-weight: 900;
}
```

### What version and implementation are you using?

Font Awesome Version: 5.7.2
Sass version: 1.17.0 compiled with dart2js 2.1.0, install with npm

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

```scss
.plugin-name {
  @import "../fontawesome-free/scss/regular.scss";
}
```

### Solution

According to [Sass issue #1251](https://github.com/sass/sass/issues/1251), Sass intentionally does not have special logic for at-rules that are top-level only. Instead, they suggest using the [@at-root](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#at-root) directive.
Change this:
```scss
@import 'variables';

@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  font-display: $fa-font-display;
  src: url('#{$fa-font-path}/fa-regular-400.eot');
  src: url('#{$fa-font-path}/fa-regular-400.eot?#iefix') format('embedded-opentype'),
  url('#{$fa-font-path}/fa-regular-400.woff2') format('woff2'),
  url('#{$fa-font-path}/fa-regular-400.woff') format('woff'),
  url('#{$fa-font-path}/fa-regular-400.ttf') format('truetype'),
  url('#{$fa-font-path}/fa-regular-400.svg#fontawesome') format('svg');
}

.far {
  font-family: 'Font Awesome 5 Free';
  font-weight: 400;
}
```
to:
```scss
@import 'variables';

@at-root {
  @font-face {
	font-family: 'Font Awesome 5 Free';
	font-style: normal;
	font-weight: 400;
	font-display: $fa-font-display;
	src: url('#{$fa-font-path}/fa-regular-400.eot');
	src: url('#{$fa-font-path}/fa-regular-400.eot?#iefix') format('embedded-opentype'),
	url('#{$fa-font-path}/fa-regular-400.woff2') format('woff2'),
	url('#{$fa-font-path}/fa-regular-400.woff') format('woff'),
	url('#{$fa-font-path}/fa-regular-400.ttf') format('truetype'),
	url('#{$fa-font-path}/fa-regular-400.svg#fontawesome') format('svg');
  }
}

.far {
  font-family: 'Font Awesome 5 Free';
  font-weight: 400;
}
```

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
