### ISSUE TITLE
Variable fa-version (scss,less) not being used in @font-face declaration

### ISSUE THREAD

**Issue by aprat84** [FortAwesome/Font-Awesome#14856]
### Describe the problem

In `_variables.[scss|less]`  file, there is a `fa-version` variable, which is not used in @font-face declaration, to force font files refresh when updating to newer versions.
Happens in both SCSS and LESS, and in every style: brands/solid/regular/light.

### What did you expect?

Font files URL should be suffixed with some query string variable to force browsers to fetch new files when updating, like it was in v4.7.0.

Something like this:

```scss
@font-face {
  font-family: 'Font Awesome 5 Pro';
  font-style: normal;
  font-weight: 900;
  font-display: $fa-font-display;
  src: url('#{$fa-font-path}/fa-solid-900.eot?v=#{$fa-version}');
  src: url('#{$fa-font-path}/fa-solid-900.eot?v=#{$fa-version}#iefix') format('embedded-opentype'),
  url('#{$fa-font-path}/fa-solid-900.woff2?v=#{$fa-version}') format('woff2'),
  url('#{$fa-font-path}/fa-solid-900.woff?v=#{$fa-version}') format('woff'),
  url('#{$fa-font-path}/fa-solid-900.ttf?v=#{$fa-version}') format('truetype'),
  url('#{$fa-font-path}/fa-solid-900.svg?v=#{$fa-version}#fontawesome') format('svg');
}
```

### What version and implementation are you using?

Version: 5.8.1

- [ ] SVG with JS
- [x] Web Fonts with SCSS/LESS
- [ ] SVG Sprites
- [ ] On the Desktop
