### ISSUE TITLE
icon half size

### ISSUE THREAD

**Issue by vurentjie** [FortAwesome/Font-Awesome#1506]
is it possible to add icon-half or icon-smaller type classes,
sometimes for example in a h1,h2 tag i want to use a smaller icon to the inherited text size, 
the other size classes (icon-2x,etc) only increase in size, so i just add something like

``` css
.icon-smaller{font-size:0.7em;}
```

when i need to
