### ISSUE TITLE
Asynchronous loading icons on page without icon

### ISSUE THREAD

**Issue by jakobdo** [FortAwesome/Font-Awesome#15326]
Hello,
we are using this approach: https://fontawesome.com/how-to-use/on-the-web/advanced/svg-asynchronous-loading

And we have this added in the global css:
```css
body {
  display: none;
}

.fontawesome-i2svg-active body {
  display: initial;
}
```

Which works great on most of our pages.
But we have a single page, where no icons are loaded, so the page stays in:
```stylesheet
body {
  display: none;
}
```
I could just add: fontawesome-i2svg-active to html on the single page, but does anyone have a better solution?
