### ISSUE TITLE
Firefox global font problem

### ISSUE THREAD

**Issue by f1234567** [FortAwesome/Font-Awesome#1610]
Is there a way I can create an exception for Font Awesome when I set a global font with css in Firefox?
# 

Font Awesome stuff breaks 

1) If I use this...

``` css
/* Global font */
*,
stub { font-family: "Trebuchet MS" !important; } 
```

...in my userContent.css - 

2) If I use Stylish

``` css
@-moz-document url-prefix("http"), 
url-prefix("file:///C:/") {
/*--------------------------------------------------------*/
/* Global font */
*,
stub { font-family: "Trebuchet MS" !important; } 
}
```
# 

I tried to figure out a way to use css not but nothing I tried worked.
# 

I'd use code tags in here if I could. But this window has zero layout stuff.
