### ISSUE TITLE
Update the documentation on the new .yarnrc.yml format for pro users

### ISSUE THREAD

**Issue by thelfensdrfer** [FortAwesome/Font-Awesome#16156]
**Describe the bug**
For yarn 2 there is a new config format, `.yarnrc.yml` (https://next.yarnpkg.com/configuration/yarnrc), 

**To Reproduce**
Install yarn 2.

**Expected behavior**
Include what you have to insert in your config file in the docs.

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by shawnheide** [comment]
I got stuck on the scope name since it has an @ sign in it. After searching around I found out that you can just drop it from the scope name. Here is what I added to my `.yarnrc.yml` to get it to authenticate properly: 
```yml
npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    npmAuthToken: "YOUR-TOKEN"

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/

**Comment by PutziSan** [comment]
Another valid configuration (`.yarnrc.yml`):

```yaml
npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: "YOUR-TOKEN"
```

**Comment by tagliala** [comment]
@shawnheide @PutziSan thanks for the heads-up

Quoting from: https://next.yarnpkg.com/configuration/yarnrc

> Environment variables can be accessed from setting definitions by using the ${NAME} syntax when defining the values. By default Yarn will require the variables to be present, but this can be turned off by using either ${NAME-fallback} (which will return fallback if NAME isn't set) or ${NAME:-fallback} (which will return fallback if NAME isn't set, or is an empty string).

Did anyone test with an environment variable instead of hard-coding the token in the configuration?

**Comment by seebeen** [comment]
Hello, I'm having issues with the above config. Seems the request is redirected to npmjs.org

![image](https://user-images.githubusercontent.com/6689756/133400533-198e241b-ffd1-4939-a6c1-4ff7c7f78368.png)

**Comment by seebeen** [comment]
For posterity, npm gives the same error

![image](https://user-images.githubusercontent.com/6689756/133400895-11d31612-dcfc-4310-b9f0-cea841b1ce61.png)

**Comment by tagliala** [comment]
Hi, there is a typo in the package name

scope: `fortawesome`
package: `fontawesome`

fo**R**tawesome in the scope is not a typo 😅

PS: I've just tried

```yml
npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: ${FONT_AWESOME_AUTH_TOKEN}
```

So with the token fetched from the environment and it works flawlessy on yarn@berry 2.4.3

Without a fallback, the above configuration throws an error if the token is not found, so it will be easy to debug

@robmadole I think that is safe to add the above snippet to the instructions for Yarn 2

**Comment by seebeen** [comment]
Well, do I feel like an idiot now 😅

**Comment by tyteen4a03** [comment]
This really should be on the Docs page.

**Comment by tagliala** [comment]
I can confirm

```yml
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONT_AWESOME_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
```

Also works on yarn 3.2

**Comment by SaavanNanavati** [comment]
Having trouble authenticating.. where are you setting your environment variable?


```
yarn add @fortawesome/fontawesome-pro  
➤ YN0027: @fortawesome/fontawesome-pro@unknown can't be resolved to a satisfying range
➤ YN0041: Invalid authentication (as an unknown user)

➤ Errors happened when preparing the environment required to run this command.
```

**Comment by EhsanKhalili** [comment]
Hi
I use yarn v3.5.1
This is my .yarnrc.yml file:
```
nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    npmRegistryServer: "https://npm.fontawesome.com/"

yarnPath: .yarn/releases/yarn-3.5.1.cjs

```
I fill npmAuthToken with my token.

but when I want to install @fortawesome/fontawesome-pro I get below error:

```

yarn add @fortawesome/fontawesome-pro
➤ YN0027: @fortawesome/fontawesome-pro@unknown can't be resolved to a satisfying range
➤ YN0041: Invalid authentication (as an unknown user)

➤ Errors happened when preparing the environment required to run this command.

```

**Comment by tagliala** [comment]
Can you please try `yarn config --why` in the folder where you are executing yarn and check if `npmScopes` looks correct?

You should see something like

```
➤ YN0000: npmScopes                     undefined, ~/fa5pro/.yarnrc.yml   Map(1) { 'fortawesome' => Map(6) { 'npmAlwaysAuth' => true, 'npmAuthIdent' => null, 'npmAuthToken' => '********', 'npmAuditRegistry' => null, 'npmPublishRegistry' => null, 'npmRegistryServer' => 'https://npm.fontawesome.com/' } }
```

**Comment by EhsanKhalili** [comment]
Here is my `npmScopes `:
```
YN0000: npmScopes                     undefined, /E:/Khalili/Private/Projects/Mountain/PAK/.yarnrc.yml   Map(1) { 'fortawesome' => Map(6) { 'npmAlwaysAuth' => true, 'npmAuthIdent' => null, 'npmAuthToken' => '********', 'npmAuditRegistry' => null, 'npmPublishRegistry' => null, 'npmRegistryServer' => 'https://npm.fontawesome.com/' } }
```

**Comment by EhsanKhalili** [comment]
<img width="641" alt="Screenshot 2023-05-14 at 2 42 13 AM" src="https://github.com/FortAwesome/Font-Awesome/assets/11146415/fa0e65f7-5405-43ff-9fbb-22d0a7fe849a">

<img width="1507" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/11146415/89553e43-0f0a-4f00-a08c-e0501aa6750f">

@tagliala What is wrong with it?
Is it yarn issue or fontawesome ?

**Comment by lorenyeung** [comment]
also having the same issue, with both Yarn 3.x and trying to resolve using NPM

**Comment by IdeaHunter** [comment]
I had the same issue, yarn version 3.6.1
Leaving note for everyone who is facing similar issue and stumbled upon this ticket

for me hardcoding npmAuthToken haven't worked however somehow using environment variable worked "${FONT_AWESOME_AUTH_TOKEN}" so there is some problem with with yarn config itself 

Then i decided to follow yarn instruction [here](https://yarnpkg.com/cli/config/set) and adjusted values accordingly by running following commands

```sh
yarn config set initScope npmScopes
yarn config set npmScopes.fortawesome.npmRegistryServer https://npm.fontawesome.com/
yarn config set npmScopes.fortawesome.npmAlwaysAuth true
yarn config set npmScopes.fortawesome.npmAuthToken XXXXX-XXX....
```

This updated yarn config similar to provided in documentation with exception of one more extra line
```yaml
initScope: npmScopes
```

Somehow this line was critical to make it work with hardcoded token

**Comment by cozzbie** [comment]
Had to install via `npmrc` before the yarn version started working. So weird.

**Comment by Kyysel** [comment]
Hi, having the same issue a while later but only in the context of a pipeline runner. My `npmScopes` is correct (checked it with `yarn config --why`). When running the installation locally it works but not when ran in the context of a pipeline runner.
The issue is detailed more specifically in this [stackoverflow post](https://stackoverflow.com/questions/78122798/gitlab-runner-invalid-authentication-to-fortawesome)
yarn version is 3.5.1

Did some people get similar issues since then? How did you solve them? Been stuck on this for a few days now.

**Comment by PawelDecowski** [comment]
Here we are, over 2 years later, and a new version of FontAwesome — still impossible to install the product I paid for. The same issue as reported above persists:

```
# yarn add '@awesome.me/kit-ddf196ced8@latest'
➤ YN0027: @awesome.me/kit-ddf196ced8@latest can't be resolved to a satisfying range
➤ YN0041: Invalid authentication (as an unknown user)
```

Even though my .yarnrc.yml is exactly as the docs say:

```
npmScopes:
  awesome.me:
    npmAlwaysAuth: true
    npmAuthToken: MY-TOKEN
    npmRegistryServer: "https://npm.fontawesome.com/"
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: MY-TOKEN
    npmRegistryServer: "https://npm.fontawesome.com/"
```
