### ISSUE TITLE
Icon Request: icon-snooze (zzz, sleep)

### ISSUE THREAD

**Issue by ghibble** [FortAwesome/Font-Awesome#1627]
Or icon-zzz

The idea is a snooze icon suggesting you are waiting for feedback or sleeping. My visual idea is 3 "z" from small (bottom left), middle, then larger top right "z". I will use it to represent that I am waiting for a response to wake up.

**Comment by nook24** [comment]
+1

**Comment by DaTebe** [comment]
+1

**Comment by ausminternet** [comment]
+1 for something like **zZz** as `fa-zzz` Icon

**Comment by phishyatl** [comment]
+1

**Comment by BrianScott1980** [comment]
+1

**Comment by MarinaMartin** [comment]
+1

**Comment by dvddmt** [comment]
:+1:

**Comment by MVcodeartbr** [comment]
could you provide one exemple?

alias +1

**Comment by nook24** [comment]
I would suggest a icon like @ghibble described it.
I created a little preview, unfortunately im not a graphics guy so i screenshot my office:
![bildschirmfoto 2015-11-30 um 11 16 36](https://cloud.githubusercontent.com/assets/9019992/11469092/5967d834-9754-11e5-8abe-951d9de138e1.png)

**Comment by dvddmt** [comment]
For example in Material icon set it looks like this:
![image](https://cloud.githubusercontent.com/assets/8076700/11470356/b585dfce-977e-11e5-8038-b77f9e0b0af4.png) [taken from here](http://glyphsearch.com/?query=snooze)
But in google inbox it looks like simple clock:
![image](https://cloud.githubusercontent.com/assets/8076700/11470376/ef940628-977e-11e5-98da-6c540853d0e8.png)

**Comment by tonyherstell** [comment]
Was hoping for a stream of Zzzz's

**Comment by tagliala** [comment]
![image](https://cloud.githubusercontent.com/assets/556268/11482893/ace6b65a-97a5-11e5-995d-2915a6437ae1.png)

Android alarm

**Comment by hashemian** [comment]
yeah, a snooze icon is really missing from the collection

**Comment by RobTS** [comment]
+1

**Comment by gs-akhan** [comment]
+1

**Comment by moerphie** [comment]
+1 👍

**Comment by nabilfreeman** [comment]
there is a way to do with with just HTML, which is what I ended up doing...

```z
<sup>
    z
    <sup>
        z
    </sup>
</sup>```

**Comment by Getterac7** [comment]
+1

**Comment by danrpts** [comment]
+1

**Comment by prowebuk** [comment]
+1

**Comment by swiftyloves** [comment]
+1

**Comment by d3artagnan** [comment]
+1

**Comment by JoeMShanahan** [comment]
+1

**Comment by vreemt** [comment]
+1
my colleague was wondering why there's a pied piper icon but no sleep/snooze one yet q:

**Comment by alparslantozan** [comment]
+1 please add this one already

**Comment by ianbamforth** [comment]
+1

**Comment by PimsJay01** [comment]
+1

**Comment by sergiohampel** [comment]
+1

**Comment by mikejavier** [comment]
+1

**Comment by KyleMit** [comment]
As a workaround (in addition to nabilfreeman's html-based solution), you could do it with html *AND CSS*

![Screenshot][0]



```css
.snooze {
  position: relative;
  font-size: 14px;
  user-select: none;
  font-family: sans-serif;
  width: 24px;
  height: 16px;
  padding-top: 9px;
  padding-left: 1px;
}
.snooze::before {
  content: "Z";
  position: absolute;
  font-size: 10px;
  left: 11px;
  top: 3px;
}
.snooze::after {
  content: "Z";
  position: absolute;
  font-size: 7px;
  left: 19px;
  top: -1px;
  font-weight: bold;
}
```



This might offer a little more customization than Plain Old HTML, and also you could keep the markup pretty consistent with other `<i class="fa fa-something"><i>` elements

[Demo in jsFiddle][2]

[0]: https://user-images.githubusercontent.com/4307307/39593797-dba2f17e-4ed8-11e8-9918-e485d4348d77.png
[1]: https://github.com/FortAwesome/Font-Awesome/issues/1627#issuecomment-205395505
[2]: https://jsfiddle.net/KyleMit/dwdnL13a/
