### ISSUE TITLE
f2dd unicode, superpower icon is not working, with version-5 free.    

### ISSUE THREAD

**Issue by maheshdeploy** [FortAwesome/Font-Awesome#16331]
**Describe the bug**
f2dd Unicode icon is not working .

 font-family: 'Font Awesome 5 Free' !important;
  content: "\f2dd";
  font-weight: 900;

Reference Link:

https://jsfiddle.net/maheshdeploy/9qxanhz8/2/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[Superpowers](https://fontawesome.com/icons/superpowers?style=brands) is a brand, please use the following syntax:

```css
.biking::before {
  font-family: "Font Awesome 5 Brands";
  font-weight: 400;
  content: "\f2dd";
}
```

Demo: https://jsfiddle.net/tagliala/p83fL5za/3/
Docs: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Hope it helps

Closing here
