### ISSUE TITLE
Certain icons not working (kaggle, wordpress-simple)

### ISSUE THREAD

**Issue by qzyu999** [FortAwesome/Font-Awesome#16669]
I'm trying to add Font Awesome icons to my jekyll website on GitHub pages. At first I was able to do this without any issue. However, I noticed that I was unable to add the fa-kaggle icon and the fa-wordpress-simple icons. I looked at previous issues but none of them seemed to be related to my problem.

works:
```
website:
  id: ''
  href: 'https://yuqizheng.com/'
  title: 'Website'
  fa-icon: 'fa-wordpress fa-2x'
```
only an empty box shows:
```
website:
  id: ''
  href: 'https://yuqizheng.com/'
  title: 'Website'
  fa-icon: 'fa-wordpress-simple fa-2x'

kaggle:
  id: 'yuqizheng'
  href: 'https://www.kaggle.com/'
  title: 'Kaggle'
  fa-icon: 'fa-kaggle fa-2x'
```
Working icons for me include: fa-envelope-square, fa-github-square, fa-linkedin-square, fa-facebook-square, fa-twitter-square, fa-instagram, fa-rss-square. Note: I'm using fa-2x also, but it doesn't work either way for the two broken icons (i.e., fa-wordpress-simple and fa-kaggle).

I was thinking this would work fine since all the other icons worked without issue. Also, the script is as follows:
```
<a href="{{ sm[key].href }}{{ sm[key].id }}" title="{{ sm[key].title }}"><i class="fa {{ sm[key].fa-icon }}"></i></a>
```
So it includes the "fa fa-wordpress fa-2x" in the script. 

Here's a screenshot with kaggle not working.
![bug](https://user-images.githubusercontent.com/34221323/82277814-a942bf00-993d-11ea-88e4-2faa155fb3bf.JPG)

Version: 5.13.0 (latest)
Browser and version: Chrome Version 81.0.4044.138 (Official Build) (64-bit) (up to date)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your application is using Font Awesome 4's syntax, which is fine, since the kit is also loading `v4 shims`. The problem is that shims work to convert old icons to the new syntax, so they do not have effect on `fa-wordpress-simple`, `fa-kaggle`, and other icons that have been introduced in 5.0.0 and 5.8.0.

My suggestion is to use FA5's syntax, so 

```yml
kaggle:
  id: 'yuqizheng'
  href: 'https://www.kaggle.com/'
  title: 'Kaggle'
  fa-icon: 'fab fa-kaggle fa-2x'  # note fab prefix
```

```html
<a href="{{ sm[key].href }}{{ sm[key].id }}" title="{{ sm[key].title }}"><i class="{{ sm[key].fa-icon }}"></i></a>
```

Please also make sure to use `fas` prefix for `envelope-square`, `rss-square`, and other icons that are not brand

Ref:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/icons/kaggle

Hope it helps

Closing here, but feel free to comment
