### ISSUE TITLE
Clock does not render well when printed to PDF via wkhtmltopdf

### ISSUE THREAD

**Issue by benjamin2k** [FortAwesome/Font-Awesome#16681]
**Describe the bug**
The icon "clock" have a bad rendering when generated inside PDF. The curve is truncated.
Tested with the three version (but not the duotone)

**To Reproduce**
PDF generation with whtmltopdf
Here is my composer.json file
`"knplabs/knp-snappy": "0.4.3",
"mpdf/mpdf": "6.0.0",
"h4cc/wkhtmltopdf-amd64": "0.12.4"`

**Expected behavior**
The circle need to be perfect :)

**Screenshots**
<a href="https://ibb.co/Y30WfJ6"><img src="https://i.ibb.co/471f4Cc/clock.png" alt="clock" border="0"></a>

**Version and implementation**
Version: Pro 5.13.0
Browser and version: does not matters

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I have noticed the same problem on a project I'm working on.

I'm going to investigate a little bit

**Comment by tagliala** [comment]
A screenshot with my stack.

It is implemented differently from yours, it is an external service which uses a containerized version of `wkhtmltox_0.12.5-1` hosted on Debian Linux 10

![image](https://user-images.githubusercontent.com/556268/82470435-9eb33180-9ac5-11ea-9a53-7a5247180f20.png)

**Comment by tagliala** [comment]
Confirmed issue

- 4.7 is also affected
- tried all the supported formats (woff2, woff, ttf)
- tried `text-rendering` variants (auto | optimizeSpeed | optimizeLegibility | geometricPrecision)

Workaround: use the `otf` file for the pdf.

```scss
/* In PDF-only stylesheet */
@font-face {
  font-family: 'Font Awesome 5 Free Print';
  font-style: normal;
  font-weight: 900;
  /* Note: OTF format is not shipped with Font Awesome web, please download it from the repo */
  src: url('url-to-your-fa-solid-900.otf') format('opentype');
}

@font-face {
  font-family: 'Font Awesome 5 Free Print';
  font-style: normal;
  font-weight: 400;
  /* Note: OTF format is not shipped with Font Awesome web, please download it from the repo */
  src: url('url-to-your-fa-regular-400.otf') format('opentype');
}

@font-face {
  font-family: 'Font Awesome 5 Brands Print';
  font-style: normal;
  font-weight: normal;
  /* Note: OTF format is not shipped with Font Awesome web, please download it from the repo */
  src: url('url-to-your-fa-brands-400.otf') format('opentype');
}

.fa,
.fas {
  font-family: 'Font Awesome 5 Free Print' !important;
}

.far {
  font-family: 'Font Awesome 5 Free Print' !important;
}

.fab {
  font-family: 'Font Awesome 5 Brands Print' !important;
}
``` 

![image](https://user-images.githubusercontent.com/556268/82475542-f012ef00-9acc-11ea-97c6-4923eea1982c.png)

Maybe there is too much optimization that does not play well with vectors generated in PDF
