### ISSUE TITLE
CSS Before is working for some icons but not for all

### ISSUE THREAD

**Issue by vbbalaji** [FortAwesome/Font-Awesome#16723]
**Describe the bug**
When I use ::before in the CSS, some icons are showing up correctly, some are not.

**To Reproduce**
my HTML Code:

```html
< !DOCTYPE HTML>
< html lang="en">
< head>
< meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
< meta name="apple-mobile-web-app-capable" content="yes">
< meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
< meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
< title>mySuccess v1.0</title>
< link rel="stylesheet" type="text/css" href="styles/bootstrap.css">
< link rel="stylesheet" type="text/css" href="styles/style.css">
< link rel="stylesheet" type="text/css" href="styles/common.css">
< link rel="stylesheet" type="text/css" href="fonts/css/all.min.css">    
< body class="theme-light" data-background="none" data-highlight="red2">
        < div class='mt-2'><i class="fas fa-block fa-2x st-red fa-building"></i></div>
        < div class='BadUp'><span class="valuenew font-weight-light">11</span></div>
         < div class="mt-n2 statText">Customers</div>
< /body>
```

My common.css:
```css
.BadUp::after, .GoodUp::after, .OkUp::after {
    content: '\f060';
    font-size: 2em;
    padding-left: 5px;
    font-family: "Font Awesome 5 Free","FontAwesome","Font Awesome 5 Pro";
    font-style: normal;
    font-weight: normal;
    text-decoration: inherit;
}
```
Now If I use \f35b, it shows up correctly, but not these: f061, f061, f062

**Version and implementation**
Version: 
 * Font Awesome Free 5.13.0 by @fontawesome - https://fontawesome.com
 * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

Browser and version: Chrome 81.0.4044

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
