### ISSUE TITLE
CORS header 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by devopsader** [FortAwesome/Font-Awesome#17402]
I'm suddenly getting errors on my kit, i tried the alternative using CDN, and that also did not work.

I'm getting the following response on page load:

```
XHROPTIONShttps://ka-f.fontawesome.com/releases/v5.15.1/css/free.min.css
[HTTP/2 403 Forbidden 1094ms]
OPTIONS
	https://ka-f.fontawesome.com/releases/v5.15.1/css/free.min.css
Status403
Forbidden
VersionHTTP/2
Transferred0.98 kB (0 B size)
    HTTP/2 403 Forbidden
    date: Fri, 13 Nov 2020 14:35:01 GMT
    content-type: text/html; charset=UTF-8
```

When trying the `example.html` file:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ka-f.fontawesome.com/releases/v5.15.1/css/free.min.css. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

**Comment by leolandotan** [comment]
Im having the same issue as well.

**Comment by yan3321** [comment]
Currently facing the same problem. Thought something was up with CORS on my server and did some fiddling, but issues still persist.

**Comment by tagliala** [comment]
I've reported this issue to hello@fontawesome.com, let's wait for feedback

**Comment by robmadole** [comment]
Can you try and run the following command and provide the output to me?

```
curl 'https://ka-f.fontawesome.com/releases/v5.15.1/css/free.min.css' \
  -X 'OPTIONS' \
  -H 'authority: ka-f.fontawesome.com' \
  -H 'accept: */*' \
  -H 'access-control-request-method: GET' \
  -H 'origin: http://localhost' \
  -H 'referer: http://localhost' \
  --compressed -v
```

**Comment by yan3321** [comment]
> Can you try and run the following command and provide the output to me?
> 
> ```
> curl 'https://ka-f.fontawesome.com/releases/v5.15.1/css/free.min.css' \
>   -X 'OPTIONS' \
>   -H 'authority: ka-f.fontawesome.com' \
>   -H 'accept: */*' \
>   -H 'access-control-request-method: GET' \
>   -H 'origin: http://localhost' \
>   -H 'referer: http://localhost' \
>   --compressed -v
> ```

Here's my output from the given script:
```
*   Trying 2606:4700:e6::ac40:ca1c:443...
* TCP_NODELAY set
* Connected to ka-f.fontawesome.com (2606:4700:e6::ac40:ca1c) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Oct 13 00:00:00 2020 GMT
*  expire date: Oct 12 23:59:59 2021 GMT
*  subjectAltName: host "ka-f.fontawesome.com" matched cert's "ka-f.fontawesome.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fffbd16baa0)
> OPTIONS /releases/v5.15.1/css/free.min.css HTTP/2
> Host: ka-f.fontawesome.com
> user-agent: curl/7.68.0
> accept-encoding: deflate, gzip, br
> authority: ka-f.fontawesome.com
> accept: */*
> access-control-request-method: GET
> origin: http://localhost
> referer: http://localhost
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200
< date: Wed, 18 Nov 2020 17:12:00 GMT
< content-length: 0
< set-cookie: __cfduid=dabf8d2cf94dd59ab2f80c132b8aad38b1605719520; expires=Fri, 18-Dec-20 17:12:00 GMT; path=/; domain=.ka-f.fontawesome.com; HttpOnly; SameSite=Lax
< access-control-allow-origin: *
< access-control-allow-methods: GET
< access-control-allow-headers: fa-kit-token
< access-control-max-age: 3000
< x-cache: Hit from cloudfront
< via: 1.1 46ddd60a6cc4c84ac6b72be6dae3d48b.cloudfront.net (CloudFront)
< x-amz-cf-pop: HKG62-C2
< x-amz-cf-id: P8x6GeDqdz1c6PY-L3956uMSdIuIoWf1LQEWjHBOTHAg21f9LRtI7w==
< age: 2561
< cf-cache-status: DYNAMIC
< cf-request-id: 067df08e07000021a651ab8000000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=M9MPT8UZNbj9wJnnb%2Fk9ZrybN69xz4TQJlzDDxhCkQbdssFPND1p7X7A3NlX0HeBpGX6Rbbhk%2FEv%2B5QL1RogPyiKYh0IFk6chlk3mQGaj9wiC7JraFl48X%2B8IfBYo03ohA%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 5f43505cdce021a6-HKG
<
* Connection #0 to host ka-f.fontawesome.com left intact
```

**Comment by yan3321** [comment]
If it helps, here's the (likely) relevant response and request headers:
![image](https://user-images.githubusercontent.com/9079480/99566447-e16bad00-2a07-11eb-9ac4-e0234e78e7d8.png)

Response:
```
HTTP/2 200 OK
date: Wed, 18 Nov 2020 17:23:03 GMT
content-type: text/css
set-cookie: __cfduid=d400d1717efd2c80489ec2eb4c2736b1e1605720183; expires=Fri, 18-Dec-20 17:23:03 GMT; path=/; domain=.ka-f.fontawesome.com; HttpOnly; SameSite=Lax
last-modified: Wed, 14 Oct 2020 21:18:07 GMT
etag: W/"319d424ba89a84bbd230a3b5f7024193"
cache-control: max-age=31556926
vary: Accept-Encoding
x-cache: Hit from cloudfront
via: 1.1 563e25ff4039f663425caf2d104a488e.cloudfront.net (CloudFront)
x-amz-cf-pop: HKG62-C2
x-amz-cf-id: 8zgUgQZV5CoN_05j3KN_maxd-Jd6xZmbqD1E3GMWW3D8z8Dawn_DHQ==
age: 32529
cf-cache-status: HIT
cf-request-id: 067dfaab7c0000196933a44000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=cIjAWN6yDkDprOTKIYFsffJUVb1bBgdhyr7Gq%2FG%2BI1Z7Nx%2BVb3UrZ7cIY39aSDpC3bxSo0jSP0nGYrQ2lT38twTEtt%2B35Lpp4jvSHx0lBqb2FxsxqbCowxp4PsJXt8Gm6g%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 5f43608bfe0d1969-HKG
content-encoding: br
X-Firefox-Spdy: h2
```
Looks like it's missing the CORS header there.

Request:
```
GET /releases/v5.15.1/css/free.min.css HTTP/2
Host: ka-f.fontawesome.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://demo.libramex.tech/login_form/login_form.html
fa-kit-token: a81368914c
Origin: https://demo.libramex.tech
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
TE: Trailers
```

**Comment by robmadole** [comment]
@yan3321 can you post the output of this?

```
curl 'https://ka-f.fontawesome.com/releases/v5.15.1/css/free.min.css' \
  -X 'GET' \
  -H 'accept: */*' \
  -H 'origin: https://demo.libramex.tech'
```

**Comment by yan3321** [comment]
> curl 'https://ka-f.fontawesome.com/releases/v5.15.1/css/free.min.css' \
>   -X 'GET' \
>   -H 'accept: */*' \
>   -H 'origin: https://demo.libramex.tech'

@robmadole Output gave me the CSS contents below (truncated since too large):

```css
/*!
 * Font Awesome Free 5.15.1 by @fontawesome - https://fontawesome.com
 * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
 */.fa,.fab,.fad,.fal,.far,.fas{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;font-variant:normal;text-rendering:auto;line-height:1}.fa-lg{font-size:1.33333em;line-height:.75em;vertical-align:-.0667em}.fa-xs{font-size:.75em}.fa-sm{font-size:.875em}.fa-1x{font-size:1em}.fa-2x{font-size:2em}.fa-3x{font-size:3em}.fa-4x{font-size:4em}.fa-5x{font-size:5em}.fa-6x{font-size:6em}.fa-7x{font-size:7em}.fa-8x{font-size:8em}.fa-9x{font-size:9em}.fa-10x{font-size:10em}.fa-fw{text-align:center;width:1.25em}.fa-ul{list-style-type:none;margin-left:2.5em;padding-left:0}.fa-ul>li{position:relative}.fa-li{left:-2em;position:absolute;text-align:center;width:2em;line-height:inherit}.fa-border{border:.08em solid #eee;border-radius:.1em;padding:.2em .25em .15em}.fa-pull-left{float:left}.fa-pull-right{float:right}.fa.fa-pull-left,.fab.fa-pull-left,.fal.fa-pull-left,.far.fa-pull-left,.fas.fa-pull-left{margin-right:.3em}.fa.fa-pull-right,.fab.fa-pull-right,.fal.fa-pull-right,.far.fa-pull-right,.fas.fa-pull-right{margin-left:.3em}...
```

Not sure if that helps though, so I also tried appending `--compressed -v` to the curl, running this:
```
curl 'https://ka-f.fontawesome.com/releases/v5.15.1/css/free.min.css' \
  -X 'GET' \
  -H 'accept: */*' \
  -H 'origin: https://demo.libramex.tech' \
  --compressed -v
```
Additional output above the CSS contents:
```
*   Trying 2606:4700:e6::ac40:ca1c:443...
* TCP_NODELAY set
* Connected to ka-f.fontawesome.com (2606:4700:e6::ac40:ca1c) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Oct 13 00:00:00 2020 GMT
*  expire date: Oct 12 23:59:59 2021 GMT
*  subjectAltName: host "ka-f.fontawesome.com" matched cert's "ka-f.fontawesome.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fffed593aa0)
> GET /releases/v5.15.1/css/free.min.css HTTP/2
> Host: ka-f.fontawesome.com
> user-agent: curl/7.68.0
> accept-encoding: deflate, gzip, br
> accept: */*
> origin: https://demo.libramex.tech
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200
< date: Wed, 18 Nov 2020 18:37:02 GMT
< content-type: text/css
< set-cookie: __cfduid=d6c25ce6e5651bbf89619c3a14dbb70be1605724622; expires=Fri, 18-Dec-20 18:37:02 GMT; path=/; domain=.ka-f.fontawesome.com; HttpOnly; SameSite=Lax
< last-modified: Wed, 14 Oct 2020 21:18:07 GMT
< etag: W/"319d424ba89a84bbd230a3b5f7024193"
< cache-control: max-age=31556926
< vary: Accept-Encoding
< x-cache: Hit from cloudfront
< via: 1.1 563e25ff4039f663425caf2d104a488e.cloudfront.net (CloudFront)
< x-amz-cf-pop: HKG62-C2
< x-amz-cf-id: 8zgUgQZV5CoN_05j3KN_maxd-Jd6xZmbqD1E3GMWW3D8z8Dawn_DHQ==
< age: 36968
< cf-cache-status: HIT
< cf-request-id: 067e3e64c8000024288e909000000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=%2FUinLW8XT1J07ajz8HFEwcMu7XmE87MMMEXsZtFTS2qaeHHKVDgAPwZuw%2FDV4lqJBLKd6TZHb2U%2FWOOnJLuOG71v0out3UwlGRhadZqks4JySgzVvMmS605nn60HXJkosg%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 5f43cce7a82b2428-HKG
< content-encoding: br
```
Still no sign of the CORS header.
