### ISSUE TITLE
Feature request: SCSS variable for font-family: FontAwesome

### ISSUE THREAD

**Issue by maxjf1** [FortAwesome/Font-Awesome#17643]
**Is your feature request related to a problem? Please describe.**
Currently, i cannot change the font-family for fontAwesome icons class selector (fa). This is useful when you need to override some icons from FontAwesome, using:

```scss
// override an FontAwesome icon symbol with an custom font icon symbol
$fa-var-search: $my-icons-search-icon;

// Makes FontAwesome as an fallback font, if the requested icon isn't found in MyIconsFont.
fa {
    font-family: MyIconsFont, FontAwesome;
}
```

Current code (explicity defines `FontAwesome` Font):

https://github.com/FortAwesome/Font-Awesome/blob/bdfa9823c8b1e25a5c822f6c719ec0e38ead7f71/scss/_core.scss#L6

**Describe the solution you'd like**
Create a simple scss variable, like `$fa-font-family`, like:

```scss
$fa-font-family: FontAwesome !default;

.#{$fa-css-prefix} {
  display: inline-block;
  font: normal normal normal #{$fa-font-size-base}/#{$fa-line-height-base} #{$fa-font-family}; // shortening font declaration
  font-size: inherit; // can't have font-size inherit on line above, so need to override
  text-rendering: auto; // optimizelegibility throws things off #1094
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

**Describe alternatives you've considered**
Just add as an extra variable, allowing to override the font-family without creating another rule

**Feature request checklist**
- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate
