### ISSUE TITLE
Icon request: icon-meds-pills 

### ISSUE THREAD

**Issue by concordian** [FortAwesome/Font-Awesome#1778]
Category: medical

icon-name:  icon-meds-pills

graphic:  2-3 loose pills (not in pill box or bill bottle)

My graphic skills aren't sufficient to create a draft.

**Comment by RVXD** [comment]
+1

**Comment by kino90** [comment]
+1

**Comment by alxfoster** [comment]
+1
Just a simple pill would be fantastic:
Eg:
![pill](https://cloud.githubusercontent.com/assets/11067158/6258540/391348e0-b77e-11e4-94f5-994da52d596c.png)

**Comment by phpforfree** [comment]
+1

**Comment by bluebit27** [comment]
+1

**Comment by Dret42** [comment]
+1

**Comment by kino90** [comment]
I've done a little 'hack' on my css file to ad a custom `.fa-pill` using `.fa-toggle-on` and a 45deg rotation.. 

Here's the code:
```css
.fa-pill{
  filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=.5);
  -webkit-transform: rotate(45deg);
  -ms-transform: rotate(45deg);
  transform: rotate(45deg);
}
.fa-pill:before {
  content: "\f205";
}	
```

It's not good as having a real icon, but it does look good!

![pill](https://cloud.githubusercontent.com/assets/1820036/7453281/d60fe616-f267-11e4-8cbf-53e688d04ab8.PNG)
