### ISSUE TITLE
svg fa-layers count positioning not working as intended

### ISSUE THREAD

**Issue by chrishough** [FortAwesome/Font-Awesome#17818]
**Describe the bug**
When I try to use fa-layers-top-right in my svg icons the position never changes, in fact it does not change for any of them. The documentation discusses `Adds a counter to the top right of your icons. Can be positioned with fa-layers-bottom-left, fa-layers-bottom-right, fa-layers-top-left and the default fa-layers-top-right. Overflow text is truncated with an ellipsis.` https://fontawesome.com/how-to-use/on-the-web/styling/layering however it does not show how this works in the example.

**To Reproduce**
Code included.

**Expected behavior**
Example Code via Slim-Lang
```slim
    div[class="icon-wrapper"]
      span[class="fa-layers fa-fw"]
        i[class="fas fa-sms"]
        span[class="fa-layers-counter fa-layers-top-right"]
          |750
```
Sample CSS
```css
  .icon-wrapper {
    padding-right: 1.5rem;

    .fa-envelope-square,
    .fa-phone-square-alt,
    .fa-sms {
      font-size: 2.5rem;
    }

    .fa-layers-counter {
      background: Tomato;
      font-size: 2rem;
    }
```

**Screenshots**
<img width="155" alt="Screen Shot 2021-04-14 at 7 38 42 AM" src="https://user-images.githubusercontent.com/744056/114729148-f4578480-9cfc-11eb-8804-cfa5edcbac11.png">

**Version and implementation**
Version: SVG with JS
Browser and version: Chrome Latest

*Thank you for your help and all the work you do*
