### ISSUE TITLE
`duotone.css` broken in beta2

### ISSUE THREAD

**Issue by mikestopcontinues** [FortAwesome/Font-Awesome#18358]
**Describe the bug**
I upgraded to beta2 to fix a few issues with beta1 (some broken duotone icons, misaligned package types), but in beta2, `duotone.css` (and `all.css`) is compiled wrong.

Here's an example:
```css
.fad.fa-0::after, .fa-duotone.fa-0::after {
  content: "\30\30"; }
```

While it seems like it should look something like this:
```css
.fad.fa-0::before, .fa-duotone.fa-0::before {
  content: "\30\fe01"; }
.fad.fa-0::after, .fa-duotone.fa-0::after {
  content: "\30\fe02"; }
```

**To Reproduce**
Just look at the css in `fontawesome-pro@6.0.0-beta2`.

**Screenshots**
Here's what it looks like:
<img width="211" alt="Screen Shot 2021-10-14 at 9 13 46 AM" src="https://user-images.githubusercontent.com/150434/137335209-1699c562-7d34-440a-a4b8-31268d413dbb.png">

**Version and implementation**
Version: 6.0.0-beta2

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Hey @mikestopcontinues.

The Unicode Variation Selectors (UVS `\fe01` and `\fe02`) were an attempt to simplify Duotone in beta1. We had a lot of issues with that approach and they kinda went up in flames after we released.

So to fix this in beta2 we completely changed the approach to go with good-ole-fashined ligatures.

The `\30\30` triggers the secondary layer. If you are seeing double icons I suspect that it could be due to an adjustment to the `letter-spacing`. Can you tell me if that value has been changed to anything other than `initial`?

**Comment by mikestopcontinues** [comment]
@robmadole Actually, it seems I made a mistake. This is the current result:

<img width="194" alt="Screen Shot 2021-10-16 at 9 50 59 AM" src="https://user-images.githubusercontent.com/150434/137592025-c4512985-5996-462a-af6c-c656c36347f6.png">

So the ligatures do seem to be working, but the primary half of the icon isn't appearing. None of the `before`s are in the css at all. It looks like the ::before is still needed:

```css
.fad.fa-0::before, .fa-duotone.fa-0::before {
  content: "\30"; }
.fad.fa-0::after, .fa-duotone.fa-0::after {
  content: "\30\30"; }
```
