### ISSUE TITLE
Duotone layers not aligned (css / firefox / non-standard font size)

### ISSUE THREAD

**Issue by iwosid** [FortAwesome/Font-Awesome#18577]
**Describe the bug**
the layers of the duotone icons are not aligned correctly in Firefox v96.0 (v95 affected too), looks ok on chrome based browser

**To Reproduce**
https://jsfiddle.net/2w05yxdk/

**Expected behavior**
icons should be aligned on all browsers

**Screenshots**
I took the screenshot of both and zoomed in the image, on the left the screenshot from chrome, on the right from firefox
![immagine](https://user-images.githubusercontent.com/88507338/149130041-a6702d93-7f8b-46cd-ad94-99c16fec3af3.png)

**Version and implementation**
Version: 6.0.0 beta 3 (from a fast test on fa-layer-group the issue is on v5.15.4)
Browser and version: Firefox v96.0 (v95 affected too)

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by iwosid** [comment]
Hi tagliala,
could you please clarify what you mean by "the issue is caused by the "null" transformation applied to the before element"? Are you referring to the below rules?

```css
.fa-duotone.fa-fw::before, .fa-duotone.fa-stack-1x::before, .fa-duotone.fa-stack-2x::before, .fad.fa-fw::before, .fad.fa-stack-1x::before, .fad.fa-stack-2x::before {
	left: 50%;
	-webkit-transform: translateX(-50%);
	transform: translateX(-50%);
}
```

Also could you please check the links in your comment? First two are the same and the last one is the link i posted.

The 16px font size is fine, sadly i can't use 16px, also if i add fa-lg layers are closer together instead of not being aligned as you can see in the below screenshot:
![immagine](https://user-images.githubusercontent.com/88507338/149146771-65564260-0eae-45cb-82fb-ebd887d9e1c7.png)
