### ISSUE TITLE
PRO version in bitbucket devops

### ISSUE THREAD

**Issue by reageek** [FortAwesome/Font-Awesome#18668]
**Describe the bug**
When attempting to use pro [.npmrc file as per docs ](https://fontawesome.com/v5/docs/web/setup/use-package-managers#environment-variables) the following error is produced. 

![image](https://user-images.githubusercontent.com/5495292/153246227-89dccb8f-37d5-49d3-8971-38d6e46e3bf0.png)

**To Reproduce**
create a .npmrc_deploy file with a environment variable reference

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONT_AWESOME_AUTH_TOKEN}
```

Go to the repo add the varaoble FONT_AWESOME_AUTH_TOKEN with pro token.

Create a bitbucket definition for compiling and installing front end assets in your bibucket yaml called node-build
```
definitions:
  steps:
    - step: &node-build
        name: Node Build
        image: node:lts
        caches:
          - node # cache node dependencies to reduce build minutes
        script: # install npm modules and build
          - mv .npmrc_deploy .npmrc
          - npm config list # list our config
          - npm install
          - npm run production
        artifacts: # save directories and files needed for deploy
          - public/**
```

Additionally in your bitbucket yaml file add a build pipeline to deploy to an environment that includes the above node build definition.
```
pipelines
  custom:
    # Deploy to Staging
    deploy-staging:
      - step: *node-build
      - step: *composer-build
      - step:
          <<: *deploy
          name: Deploy to Staging
          deployment: staging 
```

Run the pipeline and on install step you will get an error about trying to login.

![image](https://user-images.githubusercontent.com/5495292/153246710-3c34382d-7e1b-4f0e-8d48-1ec1d76b1250.png)

The license is up to date.

**Expected behavior**
I would like the package called font awesome pro from the fortawesome registry to install.

Locally I can use the nprc file with the contents and install without issue.
```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken={fontawesometoken}
```
