### ISSUE TITLE
Font Family: FontAwesome Unicode in Select Menu Elements Now Uppercases Text and uses a Weird Font Instead of just replacing the Unicode Icons.

### ISSUE THREAD

**Issue by geilt** [FortAwesome/Font-Awesome#18679]
**Describe the bug**
Having an issue. I use FontAwesome for Select Dropdown menus since my clients ALL use Chrome, and the Unicode Characters will convert when the FontAwesome Font Family is set on a Select Menu Element.

I tried to Upgrade to 6.0 today from 5, but I get this WEIRD formatting error. 

It seems the fonts not only replace the unicode with the font, but have some kind of font-embedded UPPERCASE and custom Font that is not my Fallback Fonts (Arial, san-serif)

**To Reproduce**
Here is an Example of What I am doing from 4.7 This is how it looks in my application

https://codepen.io/geilt/pen/OJOgPZX

Now here is the exact same code and method using 6.0

https://codepen.io/geilt/pen/podwvVd

Notice the Difference?

**Expected behavior**
It should work just like V4 and V5 and not change the Font Styling of Elements inside a Select Box other than the Unicode Font itself.

**Screenshots**
V4 Working
https://imgur.com/a/7Wcq4BC

V6 Broken
https://imgur.com/a/dpuWeyI

**Version and implementation**
Version: 6.0.0
Browser and version: Chrome 98.0.4758.82 

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, but this use case is not supported and can't work cross-platform, please read through #996

In versione 6, we introduced letters and numbers, so Font Awesome will behave just like a regular font

Here it is also a screenshot on macOS:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/556268/153560051-ff9a9c63-fc3f-43dd-acd5-d4e58c1d9ec3.png">

Our suggestion is to use a javascript solution for this use case

Closing here, but feel free to comment

**Comment by geilt** [comment]
Shame, I am a paid member for FontAwesome and I almost almost use this exclusively. I guess I am stuck with V4 - 5 Forever. 

I am aware that it does not work in some environments. But it does on most. Well it did, now it makes fonts the equivalent of Comic Sans.

**Comment by tagliala** [comment]
Given that:
- **I do not recommend this**
- Font Awesome does not support this use case
- Font Awesome evolved in the years
- This is use case is not cross-browser / cross-platform
- This use case cannot mix regular and solid icons in FA >= 5
- Letters and numbers will not be visible in the dropdown
- **I do not recommend this**

There is a workaround to make this work again by using `unicode-range` and excluding latin letters. I'm deliberately using a different font face to prevent issues

```css
@font-face { 
  font-family: FontAwesomeDropdown;
  font-display: block;
  font-weight: 900;
  src: url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/webfonts/fa-solid-900.woff2") format("woff2");
  unicode-range: U+0080-10FFFF;
}
@font-face { 
  font-family: FontAwesomeDropdown;
  font-display: block;
  font-weight: 900;
  src: url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/webfonts/fa-brands-400.woff2") format("woff2");
  unicode-range: U+0080-10FFFF;
}
```

Browser support: https://caniuse.com/font-unicode-range

https://jsfiddle.net/tagliala/9fd4yto6/5/
