### ISSUE TITLE
"https://npm.fontawesome.com/@fortawesome%2ffontawesome-free: authentication required".

### ISSUE THREAD

**Issue by pedro-profile** [FortAwesome/Font-Awesome#18942]
When i run below command i get error.

root@wjd8:/mnt/c/xampp/htdocs/bedrock/web/app/themes/wraith# yarn add @fortawesome/fontawesome-free
yarn add v1.22.18
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffontawesome-free: authentication required".
info If you think this is a bug, please open a bug report with the information provided in "/mnt/c/xampp/htdocs/bedrock/web/app/themes/wraith/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Here's the yarn-error.log 
https://zerobin.net/?0d11329be96bd878#2oxyiKh2Cy0fX9LTiMY/HP7L8MRPNk49TstSnBk5lKU=

What's the fix for this?

**Comment by tagliala** [comment]
Hi, are you a Font Awesome Pro customer?

**Comment by pedro-profile** [comment]
> Hi, are you a Font Awesome Pro customer?

I am developing a Sage based theme for a company. 
Should i ask them about the Font Awesome Pro login details?

What is necessary to run "yarn" inside the theme without that error?

**Comment by tagliala** [comment]
> I am developing a Sage based theme for a company.

Hi, sorry I do not know this theme and this repository is not intended to report third-party issues

> What is necessary to run "yarn" inside the theme without that error?

Uninstall `@fortawesome/fontawesome-free` and installing it back, after making sure that `.npmrc` does not contain a configuration that points `@fortawesome/fontawesome-free` to the private npm repository `https://npm.fontawesome.com`

You may want to take a look at #15964

**Comment by SamEdwards-1** [comment]
I am having the same issue. I am a pro customer, my company uses yarn, and i have an .npmrc file in the correct place as described in https://fontawesome.com/docs/web/setup/packages.

What is unclear is the mechanism by which that registry setting with authToken is applied to yarn. The .npmrc approach didnt work, nor did using npm config variables.

**Comment by tagliala** [comment]
> What is unclear is the mechanism by which that registry setting with authToken is applied to yarn. 

Hi, which version of yarn?

In yarn 1, you can use `yarn config list --verbose` to check how `.npmrc` logic applies to yarn and if Font Awesome configuration is correct 

PS: as a pro customer, you can ask for dedicated support at hello@fontawesome.com

**Comment by SamEdwards-1** [comment]
Yeah, this was to the top result in a google search though....

Anyway, long story short, in my case it turned out to be a Docker thing, the .npmrc approach for yarn worked once the containers were removed and rebuilt.

/shrug

**Comment by jaketrimble** [comment]
For anyone searching for a solution. I hope this helps.

**Locally**
Replace `YOUR_FONT_AWESOME_NPM_TOKEN` with your own found [here](https://fontawesome.com/account#pro-package-tokens).
```
npm config set "@fortawesome:registry" https://npm.fontawesome.com/
npm config set "//npm.fontawesome.com/:_authToken" "YOUR_FONT_AWESOME_NPM_TOKEN"
yarn add @fortawesome/fontawesome-pro
```

**CircleCI example**
This assumes you have `YOUR_FONT_AWESOME_NPM_TOKEN` in your CircleCI project's Environment Variables
```
commands:
  setup-font-awesome-token:
    steps:
      - run:
          name: Set token Font Awesome Pro
          command: |
            npm config set "@fortawesome:registry" https://npm.fontawesome.com/
            npm config set "//npm.fontawesome.com/:_authToken" "${YOUR_FONT_AWESOME_NPM_TOKEN}"
...
jobs:
  build:
    ...
    steps:
      - ...your initial steps
      - setup-font-awesome-token
      - run: yarn install
````
