### ISSUE TITLE
FontAwesome free v6.0 e3d6 did not show 

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#18943]
Fontawesome icon  arrow turn-down-right (e3d6 )did not show, just a red square showed. 
code: 
HmtL

```html
<i class="fa-solid fa-arrow-turn-down-right"></i>
```

css: 
```css
#thisIcon::before{
font-family: "Font Awesome 6 Free"; 
font-weight: 400;
content: "\e3d6";
color: red; 
font-size: 40px; 
color: lightgray;
}
```
