### ISSUE TITLE
Bug: scss/_list.scss throws error on compilation

### ISSUE THREAD

**Issue by anthonypwinning** [FortAwesome/Font-Awesome#19078]
### Bug description

When I attempt to compile FontAwsome as a yarn package with Sass, _scss/_list.scss_ appears to be the source of an error that prevents compilation.

I believe:

`  left: calc(var(--#{$fa-css-prefix}-li-width, #{$fa-li-width}) * -1);`

Should be:

`  left: var(--#{$fa-css-prefix}-li-width, calc(#{$fa-li-width} * -1));`

Everything works fine after changing that one line. I'll add a pull request with this code change.

### Font Awesome version

v6.1.1

### Serving

Self-hosted

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Chrome Version 101.0.4951.64 (Official Build) (x86_64) on MacOS

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.



> I believe:
> 
> ` left: calc(var(--#{$fa-css-prefix}-li-width, #{$fa-li-width}) * -1);`
> 
> Should be:
> 
> ` left: var(--#{$fa-css-prefix}-li-width, calc(#{$fa-li-width} * -1));`

As far as I can see, they are not the same thing

```scss
$fa-css-prefix: "fa";
$fa-li-width: 2em;

:root {
    --#{$fa-css-prefix}-li-width: #{$fa-li-width};
}

.before {
    left: calc(var(--#{$fa-css-prefix}-li-width, #{$fa-li-width}) * -1);
}

.after {
    left: var(--#{$fa-css-prefix}-li-width, calc(#{$fa-li-width} * -1));
}
```

compiles to

```css
:root {
  --fa-li-width: 2em;
}

.before {
  left: calc(var(--fa-li-width, 2em) * -1);
}

.after {
  left: var(--fa-li-width, calc(2em * -1));
}
```

Demo: https://jsfiddle.net/tagliala/uz7b1wha/3/

Are you using a custom value for $fa-li-width? Could you please provide more details about the error you are getting?
