### ISSUE TITLE
Bug: Icons appears where fonts should be

### ISSUE THREAD

**Issue by ash-wicket** [FortAwesome/Font-Awesome#19292]
### Bug description

We're currently using FA and occasionally we get weird glyphs where the icons should be. We've seen several postings about this and tried the solutions but to no avail. We were hoping someone could see if they could spot what we're missing.
Thanks 

Here's the dev url https://authorsguild-website-wordpress.ind.ninja/

### Font Awesome version

v6.0.0

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

Chrome, Firefox both latest and older versions

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see that the website is using Font Awesome 6 Pro with a self-hosted CSS and a slightly custom implementation, through a third party theme

We do not provide support for third party libraries/themes/plugin, so if you are not the developer of the theme this is not the proper place to report an issue.

I can see that the output css is not correctly escaping the `content` attribute for some CSS icons.

Example: https://authorsguild-website-wordpress.ind.ninja/app/themes/industrial/assets/styles/min/industrial.min.css?ver=1661877906

```css
.header #header-secondary li.donate a::before, header #header-secondary li.donate a::before {
    content: ""; /* The problem is here. Should be content: "\f4be"; */
    font-family: "Font Awesome 6 Pro";
    color: rgb(12, 117, 112);
    font-weight: 300;
    font-size: 1.2rem;
}
```

Correct example, from https://authorsguild-website-wordpress.ind.ninja/app/themes/industrial/assets/fonts/FontAwesome/web-fonts-with-css/css/all.css?ver=1658238902

```css
.fa-hand-holding-heart::before {
  content: "\f4be"; }
```

There is a known issue with CSS + Sass + self-host implementation that may randomly lead to this kind of issues

Ref: #17644 - you will find a workaround

Closing here (as a duplicate of #17644), but feel free to comment.
