### ISSUE TITLE
Bug: error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome%2fpro-light-svg-icons: Not found".

### ISSUE THREAD

**Issue by daningalla** [FortAwesome/Font-Awesome#19458]
### Bug description

Related to [15332](https://github.com/FortAwesome/Font-Awesome/issues/15332)...

Following the exact instructions [here](https://fontawesome.com/docs/web/setup/packages#installing-pro), I get the following error in my Docker build:

```
#11 7.524 error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome%2fpro-light-svg-icons: Not found".
```

Here is my .yarnrc.yaml file:

```
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com"
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"
```

If it matters, here is the Dockerfile:
```
FROM node:14.15.4 as node
WORKDIR /app
COPY . .
RUN npm install yarn
RUN rm package-lock.json
RUN yarn install
RUN npm run build

FROM nginx:alpine
COPY --from=node /app/dist/angular-app /user/share/nginx/html
```

### Font Awesome version

v6.2.0

### Serving

Other (as specified in the bug description)

### Implementation

SVG+JS

### Browser and Operating System

N/A

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
