### ISSUE TITLE
Bug: Font version mismatch beteween the brands @font-face declaration and the usage with the css class .fa-brands

### ISSUE THREAD

**Issue by TomAchT** [FortAwesome/Font-Awesome#19734]
### Bug description

In the **all.css** file from a downloaded kit, the versions of font-familiy are different: 5 vs 6. The font are therefore not requested and th brands icons are not rendered.

```css
.fab,
.fa-brands {
  font-family: 'Font Awesome 6 Brands'; }
```

```css
@font-face {
  font-family: 'Font Awesome 5 Brands';
  font-display: block;
  font-weight: 400;
  src: url("../webfonts/fa-brands-400.woff2") format("woff2"), url("../webfonts/fa-brands-400.ttf") format("truetype"); }
```

### Font Awesome version

v6.4.0

### Application and Operating System

In the all.css file generated for web usage.

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
