### ISSUE TITLE
Bug: Icon missing in version 6

### ISSUE THREAD

**Issue by craftzneko** [FortAwesome/Font-Awesome#20138]
### Bug description

This could be me misunderstanding but the window icon seems to appear when searching on version 6

![image](https://github.com/FortAwesome/Font-Awesome/assets/662108/7ce33b65-5d4c-4b2d-a294-9ce09f6d5a78)

But when referring to it in CSS

``` CSS
@import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css');

label[for*='ICT-side-tab2']:before {
  content: '\f17a';
}
```

I get this

![image](https://github.com/FortAwesome/Font-Awesome/assets/662108/85e2fd23-1bf8-4d3e-be79-2f10f13f80f1)

### Font Awesome version

v6.5.1

### Serving

Font Awesome CDN

### Implementation

CSS

### Browser and Operating System

WIndows 10
Edge latest

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
