### ISSUE TITLE
Bug: 404 tarball install when `npm install` on Github Actions

### ISSUE THREAD

**Issue by claytonrothschild** [FortAwesome/Font-Awesome#20358]
### Bug description

I can run `npm install` for `@fortawesome/free-solid-svg-icons@6.6.0` locally, no problem. But when I run it as part of a github action on `ubuntu-latest` worker, I get this error:
```
npm error 404 Not Found - GET https://registry.npmjs.org/@fortawesome/free-solid-svg-icons';/free-solid-svg-icons-6.6.0.tgz
npm error 404
npm error 404  '@fortawesome/free-solid-svg-icons@https://registry.npmjs.org/@fortawesome/free-solid-svg-icons';/free-solid-svg-icons-6.6.0.tgz' is not in this registry.
npm error 404
```

Github Action:

```yaml
name: Lint, Test, Build, and Preview

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}    # Checkout the current branch

    - name: Install ESLint and @eslint/js
      run: npm i -D
 ```

`package.json`:
```json
    "@fortawesome/fontawesome-free": "^6.6.0",
    "@fortawesome/free-solid-svg-icons": "^6.6.0",
 ```
 
 I understand there is some talk of an auth token, but I understand that is only for the pro packages. 
 
Indeed, I can see the missing package that it says is 404. The error appears to be due to how the worker is parsing `https://registry.npmjs.org/@fortawesome/free-solid-svg-icons/-/free-solid-svg-icons-6.6.0.tgz` into `https://registry.npmjs.org/@fortawesome/free-solid-svg-icons';/free-solid-svg-icons-6.6.0.tgz` which results in the 404.

### Font Awesome version

v6.6.0

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

ubuntu-latest on Github Actions Workers

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
