### ISSUE TITLE
New 4.0 + 3.2.1 backward compatibility?

### ISSUE THREAD

**Issue by tennisgent** [FortAwesome/Font-Awesome#2236]
Can we get a version of font awesome that has duplicate class names for all of the old `icon-*` naming conventions?  I want to upgrade to use the new 4.0 icons but I have tons of markup that includes the old syntax and I don't want to have to redo all of that.  

I don't think it would be that hard.  You would just have something like:

``` css
.fa-star:before, .icon-star:before{
  content: "\f005";
}
```

Or is there some other obstacle that I'm not seeing?
