### ISSUE TITLE
Icon Request: "dummy" icon

### ISSUE THREAD

**Issue by nbvcxz** [FortAwesome/Font-Awesome#2326]
Not a typical request but I try to clear what could help to develop Font-Awesome with 3rd part SVG icons.
So - mine and more people problem is to add own SVG icons to (brillant :) ) Font Awesome. Of course there are few sites eg: http://icomoon.io/ or http://fontcustom.com/ . But I found them complicated and sometimes buggy (can not convert SVG).
Looking for a way to directly insert SVG picture to HTML code but preserve existing Font Awesome classes (to have everything looking as in FA) I made a small dirty hack:

``` css
.fa-my-icon:before {
    content: "\f039"; /* So far I use transparent adjust sign - here would be nice to have a dummy transparent sign with size of adjust icon to allow proper scaling  */
    color: transparent; /* This is a cheat - in case of dummy icon it would be redundant I think */
    background: url(http://url.to/your/icon.svg); /* Here path to our icon in SVG */
    background-repeat:no-repeat;
    background-position:center;
}
```

I hope this idea can be understood. I think it could help to test new icons and faster develop Font Awesome as well as expand fontset with own icons with no need of "recompilation".
