### ISSUE TITLE
Icon request: sim-card

### ISSUE THREAD

**Issue by fuxio82** [FortAwesome/Font-Awesome#2445]
Hi, I am missing an icon for sim card.
I'll use it for the section "sim card" of the user equipment in my webapp named "equipment".

![sim-card](https://f.cloud.github.com/assets/5990401/1581608/3acfa97c-51da-11e3-841e-49925a7b36bb.jpg)

**Comment by vdemin** [comment]
+1

**Comment by lairsdragon** [comment]
+1

**Comment by ntvsx193** [comment]
+1

**Comment by thomazfeitoza** [comment]
+1

**Comment by cyriloatley** [comment]
+1

**Comment by aroon9002ahmed** [comment]
+1

**Comment by sunsys0** [comment]
+1

**Comment by tomcashman** [comment]
+1

**Comment by AliAlGallaf** [comment]
+1

**Comment by csoseman** [comment]
+1

**Comment by qu1cke** [comment]
+1

**Comment by AnaArede** [comment]
+1

**Comment by AMetnik** [comment]
+1

**Comment by jotakaef** [comment]
+1 !

**Comment by rafilathif** [comment]
+1

**Comment by nghiacr002** [comment]
+1

**Comment by amir110** [comment]
+1

**Comment by educationisenemy** [comment]
+1

**Comment by WhiteRoyal** [comment]
+1

**Comment by tryton-vanmeer** [comment]
+1

**Comment by amethegreat** [comment]
+1

**Comment by HawkiesZA** [comment]
+1

**Comment by sourabhkejriwal** [comment]
+1

**Comment by emilianopenedo** [comment]
+1

**Comment by tryton-vanmeer** [comment]
+1

**Comment by gdejong** [comment]
+1

**Comment by lucajick** [comment]
+1
![mobile-03-512](https://cloud.githubusercontent.com/assets/25476335/22511674/b06cc8f8-e896-11e6-9b27-70a3874e1b36.png)

**Comment by joelatty** [comment]
+1

**Comment by marcioferreirap** [comment]
+1

**Comment by leenyx** [comment]
+1

**Comment by batyrkhan14** [comment]
+1

**Comment by austinarmbruster-tc** [comment]
+1

**Comment by moshmage** [comment]
@tagliala any plans on adding this icon?

**Comment by PetyoKostakov** [comment]
+1

**Comment by githubjeka** [comment]
+1

**Comment by NicolaZaltron** [comment]
+1

**Comment by LuisaZurlo** [comment]
+1

**Comment by mjstecson** [comment]
+1

**Comment by brunchto** [comment]
+1
maybe add a variant "sam-card" for secure access card : https://en.wikipedia.org/wiki/Secure_access_module
which could have the same form factor.

**Comment by agata-borkowska** [comment]
+1

**Comment by geekzolanos** [comment]
+1

**Comment by MrGreyKnight** [comment]
+1

**Comment by JHarrowell** [comment]
+1

**Comment by githubjeka** [comment]
`<i class="sim-image"></i>`

```css
.sim-image {
    width: 48px;
    height: 48px;
    margin-right: 25px;
    background-image: url(data:image/svg+xml;utf8;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNv…9nPgo8Zz4KPC9nPgo8Zz4KPC9nPgo8Zz4KPC9nPgo8Zz4KPC9nPgo8Zz4KPC9nPgo8L3N2Zz4K);
    background-size: 48px;
    background-repeat: no-repeat;
    display: block;
}
```
