### ISSUE TITLE
sprites.less reset section missing from less, sass, and scss

### ISSUE THREAD

**Issue by jordandh** [FortAwesome/Font-Awesome#275]
Unless I am missing a build step I believe that the less, sass, and scss files are all missing the sprites.less reset styles. This section appears in the css files themselves but not the less, sass, and scss files.

``` css
/* sprites.less reset */
[class^="icon-"],
[class*=" icon-"] {
    display: inline;
    width: auto;
    height: auto;
    line-height: inherit;
    vertical-align: baseline;
    background-image: none;
    background-position: 0% 0%;
    background-repeat: repeat;
}
li[class^="icon-"],
li[class*=" icon-"] {
    display: block;
}
```
