### ISSUE TITLE
Request for non-breaking space

### ISSUE THREAD

**Issue by replete** [FortAwesome/Font-Awesome#304]
Here's the use-case:
![Use-case for Non-breaking space](http://content.screencast.com/users/replete/folders/Jing/media/61c3dcbf-1209-4ae4-940c-0205d28c19f7/2012-06-26_1501.png)

I'm using font-awesome to display sorting icons in a table header. Rather than using icon-classes, I am using :after content CSS definitions like so:

``` css
    th[class*=sorting]:after {
    font-family:FontAwesome;
    content:"\f0dc";
    font-size:11px;
    color:@baseAccent3;
    font-weight:normal !important;
    line-height:1em
    }

    th.sorting_asc:after {
    content:"\f0de";}

    th.sorting_desc:after {
    content:"\f0dd";}

```

The problem with the above, is that it requires a bit of extra space to the left of the sorting symbols next to the text. This could be fixed by making the `:after` content `display:block` but that causes the sorting symbol to drop off the line when the table is resized smaller. Basically, the symbol _must_ be visually associated with the accompanying text.

I'd like to request that a space is allocated appropriately (as with other fonts), after which the following solution will work as desired (replacing _/0000_ with the space code:

``` css
    th[class*=sorting]:after {
    font-family:FontAwesome;
    content:"\0000\f0dc";
    font-size:11px;
    color:@baseAccent3;
    font-weight:normal !important;
    line-height:1em
    }
```
