### ISSUE TITLE
Icon Request: fa-stack-overflow-square

### ISSUE THREAD

**Issue by sealocal** [FortAwesome/Font-Awesome#3190]
I would like to see an alternative to the `fa-stack-overflow` icon.  I am using 'square' icons and would like to keep them consistent.

I tried using the `fa-inverse` class, but it did not affect the stack-overflow icon.

For guidelines, compare these:
`fa-linkedin` vs. `fa-linkedin-square`
`fa-twitter` vs. `fa-twitter-square`
`fa-github` vs. `fa-github-square`
`fa-tumblr` vs. `fa-tumblr-square`
`fa-pinterest` vs. `fa-pinterest-square`

P.S. If someone could point me to a guide to adding a new icon, I would attempt to invert the `fa-stack-overflow` icon myself.

**Comment by marksilvis** [comment]
+1, a square option would make it much neater looking next other icons.

**Comment by bastienleonard** [comment]
+1, I need this to add a Stack Overflow icon to my site.

**Comment by sealocal** [comment]
I used CSS to create the effect.

![screen shot 2015-10-31 at 5 17 43 pm](https://cloud.githubusercontent.com/assets/4951910/10866602/5e7fcc32-7ff3-11e5-83bc-5d0274a324e0.png)


```css
.fa-stack-overflow.fa-5x {
  position: relative;
  top: -.2em;
  padding: .2em;
  font-size: 3em;
  color: #eee;
  background-color: #000;
  border-radius: 0.2em;
  width: 1em;
  text-align: center;
}
```
