### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by muhammad-saleh** [FortAwesome/Font-Awesome#3505]
Dears,
I'm making a rating component and it supports RTL and after using your great font I found that all of your half full / half empty stars looks right only with LTR applications

In LTR the empty side is on the right which is correct
In RTL the empty side is on the right too which unfortunately is wrong

Images to explain:
LTR:
http://imgur.com/HxgorFe

RTL:
http://imgur.com/BUWjdWk

Stars Icons you have:
http://imgur.com/glwNNBC
as you can see the full side of the half empty star is always on the left

Thanks.

**Comment by MohammadYounes** [comment]
You can control icons direction using the following CSS:

```CSS
[dir=ltr].fa-dir-flip .fa.fa-flip-horizontal,
[dir=rtl].fa-dir-flip .fa,
[dir=rtl] .fa.fa-dir-flip {
  filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1);
  -webkit-transform: scale(-1, 1);
      -ms-transform: scale(-1, 1);
          transform: scale(-1, 1);
}
[dir=rtl].fa-dir-flip .fa-flip-horizontal,
[dir=ltr].fa-dir-flip .fa,
[dir=ltr] .fa.fa-dir-flip {
  filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=0);
  -webkit-transform: scale(1, 1);
      -ms-transform: scale(1, 1);
          transform: scale(1, 1);
}
*:not([dir=rtl]) [dir=ltr] .fa.fa-dir-flip {
  filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=0)!important;
  -webkit-transform: scale(1, 1)!important;
      -ms-transform: scale(1, 1)!important;
          transform: scale(1, 1)!important;
}

*:not([dir=ltr]) [dir=rtl] .fa.fa-dir-flip {
  filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)!important;
  -webkit-transform: scale(-1, 1)!important;
      -ms-transform: scale(-1, 1)!important;
          transform: scale(-1, 1)!important;
}
```

It gives you the ability to do global and local flip for `.fa` icons (**[live demo](http://codepen.io/anon/pen/zxeRmG)**)

  1. Globally, add direction attribute `dir="rtl"` and `fa-dir-flip` class:

    ```html
    <html dir="rtl" class="fa-dir-flip">
     .
     .
        <!-- this will be RTL -->
        <span class="fa fa-arrow-left"></span>
     .
     .   
    <html>
    ```

  2. Locally, add direction attribute `dir="rtl"` to the container and `fa-dir-flip` class to the icon you want to flip.

    ```html
    <html dir="rtl">  
     .
     .
         <div dir="ltr">
             <!-- this will be LTR -->
             <span class="fa fa-arrow-left fa-dir-flip"></span>
             <!-- this will be RTL, falling back to the farthest ancestor direction -->
             <span class="fa fa-arrow-left"></span>
         </div>       
     .
     .
    </html>
    ```



PR ?

**Comment by fisharebest** [comment]
FYI, this is the solution I use in my projects:
https://github.com/fisharebest/font-awesome-rtl

**Comment by molerat619** [comment]
Hi, thanks for the ideas here - I like the approaches. But how can we actually use this now? Has anything been integrated?

**Comment by evilaliv3** [comment]
@MahdiMajidzadeh: How difficult would be to implement for font awesome 5 the same thing that you have implemented for bootstrap 3 that was using glyphicons?

**Comment by sensibleworld** [comment]
Doing a little management in Github and (batch) closing out potentially stale issues. If the above still needs attention, please let us know and we’ll re-open!

**Comment by leoraez** [comment]
@sensibleworld: this is still outstanding. I feel people just started using overrides as some mentioned above:
- https://github.com/fisharebest/font-awesome-rtl by @fisharebest 
- https://gist.github.com/MohammadYounes/3d8af806cd80ad6bbe94 by @MohammadYounes 

In our team the most common cases we've had to fix were arrows, chevrons, etc. which had a `-left` or `-right` suffix in their name. e.g: `fa-chevron-left`

We are currently testing something like:

```scss
.icon {
   &[class*="-left"]:dir(rtl),
   &[class*="-right"]:dir(rtl) {
        transform: scaleX(-1);
    }
}
```

to match selectors like: `.icon.fa-chevron-left` (icon is our element for this purpose)

Should FontAwesome provide icons with natural support for RTL, consider a version of `-left` and `-right` icons suffixed with `-start` and `-end`: its usage would be more intentional and controlled by authors. e.g. `fa-chevron-end`

A note on the `fa-flip-horizontal` solution. This requires actively **adding** the class on the required scenarios (not pure CSS).  We could provide an utility class like `fa-flip-rtl`, `fa-flip-dir` or `fa-flip-inline` that would perform the horizontal mirror on RTL.

Thanks for the _Awesome_ work!
