### ISSUE TITLE
Tiny subset icons via fa-sub (fa-sup) overlay

### ISSUE THREAD

**Issue by gandalfx** [FortAwesome/Font-Awesome#3640]
There are a lot of bitmap Icons out there that have some sort of mini-icons attached to them to indicate a dropdown menu etc. So far I have not found anything similar for FontAwesome even though it should be feasible.

Here are a few examples I am currently using in a project:
![example image](http://i.imgur.com/bA7336s.png)
Another likely candidate would of course be `fa-caret-down` to indicate some kind of context menu.

I don't have a pull request for this but here is an example implementation that has worked for me so far:

``` HTML
<span>
    <i class="fa fa-lg fa-fw fa-picture-o"></i>
    <i class="fa fa-sub fa-upload"></i>
</span>
```

``` CSS
// use with .fa-fw.fa-lg on main icon
.fa-sub {
    position: relative;
    left: -.8em;
    width: .2em;
    vertical-align: -.25em;
    text-shadow: 0 0 1px black; // optional contrast
}
```

So as you can see it's a similar principle to `fa-stack`

For completeness sake you might also want to add a `fa-sup` class for mini icons oriented at the top, e.g. for use as quirky footnote indicators.

Again I appologize if this has been suggested before, there are a lot of issues and afaik no search function for them.
In any case great work so far, really appreciate it. Cheers!
