### ISSUE TITLE
stacked icons are not rotated in IE8

### ISSUE THREAD

**Issue by blatan** [FortAwesome/Font-Awesome#4055]
Hi,
our tester found and I resolved the problem in IE8.

Build a stack. Add rotating class to the stack. The icons inside are not rotated.

My solution:

``` css
.ie8 .rocheicon-stack[class*="faicon-rotate-"] .rocheicon {
    filter: inherit;
}
```

Regards,
Bernard
