### ISSUE TITLE
Icon Request: fa-star-quarter-empty and fa-star-3/4-empty

### ISSUE THREAD

**Issue by marblemass** [FortAwesome/Font-Awesome#4147]
At the moment the icons in Font-Awesome have a full star or a half star. I am requesting new icons for quarter and 3/4 filled stars.

It would be useful for display in a rating system.

**Comment by nicowens** [comment]
This request gets a definite fa-thumbs-o-up from me!

USE CASE

RE: the following page:
http://www.popyachts.com/reviews

We display our reviews found on various websites, singly and in aggregate.  When we have something like a 4.94, we round that up to 5.0.  When we have something like a 4.7, it ends up rounding down to 4.5 stars.  Well that just stinks!  I'd really much prefer to round it to 4.75 stars!

![image](https://cloud.githubusercontent.com/assets/10542820/5753263/049751e6-9c54-11e4-873d-82e3d4e0df0c.png)

**Comment by jayjamero** [comment]
For those looking for a solution this may help!

http://codepen.io/denwo/pen/azjXzL

```html
<div class="star_rating">2.5</div>
```

```scss
.star_rating {
  position: relative;
  display: inline-block;
  letter-spacing:5px;
  
  &:before {
    display:block;
    font-size:500%;
    top:0;
    left:0;
    font-family: FontAwesome;
    content: "\f005\f005\f005\f005\f005";
    color: #818181;
    text-shadow: 0 2px darken(#818181,20%);
    padding-left:5px;
  }
  span {
    position:absolute;
    top:0;
    left:0;
    height:100%;
    display:block;
    overflow:hidden;
    &:before{
      font-size:500%;
      font-family: FontAwesome;
      color: #ffbb00;
      position: absolute;
      left: 0;
      top:0;
      content:"\f005\f005\f005\f005\f005";
      text-shadow: 0 1px darken(#ffbb00, 20%);
      display:block;
      padding-left:5px;
    }
  }
}
```

```javascript
$.fn.rating = function() {
    var val = 0, size = 0, stars = 5;
    return this.each(function(i,e){ val = parseFloat($(e).text()); size = ( $(e).width() / stars ); $(e).html($('<span/>').animate({ width: val * size }, 1000 ) ); });
};
```

**Comment by AnMartini** [comment]
+1

**Comment by maurice85** [comment]
its 2019 now, has there been any progress made? Really need it!

**Comment by hassan-tariq** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’ve added this issue to our new list to be created! We can’t promise any firm timelines right now, but this will help us keep track of it.

We’ll update this issue when the icon is released into the wild 🙂

**Comment by JonLaliberte** [comment]
Anyone here in the future, you can do this without JS in modern browsers:

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<div class="star-rating" style="--rating: 3.35;" aria-label="2.35 out of 5">
  <div class="star-rating__base"></div>
  <div class="star-rating__fill"></div>
</div>
```

```css
.star-rating {
  --stars: 5;
  --star-size: 2rem;           /* adjust */
  --star-color-empty: #818181;
  --star-color-fill: #ffbb00;

  position: relative;
  display: inline-block;
  font-size: var(--star-size);
  line-height: 1;
}

/* gray stars */
.star-rating__base::before {
  content: "\f005\f005\f005\f005\f005";
  font-family: "FontAwesome";
  color: var(--star-color-empty);
  letter-spacing: 0.25rem;
}

/* filled overlay */
.star-rating__fill {
  position: absolute;
  inset: 0;
  overflow: hidden;
  width: calc(var(--rating) / var(--stars) * 100%);
  transition: width 0.4s ease;
}

.star-rating__fill::before {
  content: "\f005\f005\f005\f005\f005";
  font-family: "FontAwesome";
  color: var(--star-color-fill);
  letter-spacing: 0.25rem;
}
```
