### ISSUE TITLE
font-awesome.css appears to be out of sync with font-awesome.less

### ISSUE THREAD

**Issue by c0bra** [FortAwesome/Font-Awesome#487]
In the .css file you have this:

``` css
/* makes the font 33% larger relative to the icon container */
.icon-large:before {
  vertical-align: top;
  font-size: 1.3333333333333333em;
}
```

While in the .less one there's this:

``` css
/* makes the font 33% larger relative to the icon container */
.icon-large:before {
  vertical-align: middle;
  font-size: 4/3em;
}
```

Note the vertical-align change.

Additionally I am having a heck of a time with the spacing between icons and following text: http://oi45.tinypic.com/16ib3nk.jpg

Not sure if its because I'm using Bootstrap v2.1.1 or what. I tried using Font-Awesome's own site.css that runs on their github page and it didn't seem to help. Very strange.
