### ISSUE TITLE
LESS: wrong relative font-path

### ISSUE THREAD

**Issue by KOTRET** [FortAwesome/Font-Awesome#497]
it seems the font-path gets resolved wrong in LESS.
It uses a path relative to the compiled less-file. If you just `@include` it in bootstrap.less and the font-awesome less-file is located in another directory, then the `@fontAwesomePath` will break.

i fixed that for me in the following way:

``` css
@font-face {
  font-family: 'FontAwesome';
  src: ~"url('@{fontAwesomePath}/fontawesome-webfont.eot')";
  src: ~"url('@{fontAwesomePath}/fontawesome-webfont.eot?#iefix')" format('embedded-opentype'),
    ~"url('@{fontAwesomePath}/fontawesome-webfont.woff')" format('woff'),
    ~"url('@{fontAwesomePath}/fontawesome-webfont.ttf')" format('truetype'),
    ~"url('@{fontAwesomePath}/fontawesome-webfont.svg#FontAwesome')" format('svg');
 ...
}
```
