### ISSUE TITLE
Unexpected CSS token on Safari

### ISSUE THREAD

**Issue by juliusosokinas** [FortAwesome/Font-Awesome#5043]
I do get 5 warnings with "Unexpected CSS token: :" on Safari for Mac browser (on line 4, though it's minimised).

Using CDN: maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css

**Comment by whitecat** [comment]
So was this fixed or was it just ignored?

**Comment by tagliala** [comment]
@whitecat https://github.com/FortAwesome/Font-Awesome/issues/5043#issuecomment-64542194

**Comment by MiguelMike** [comment]
Ok, the solution is to place IE filters in dubble quotes. Has this already been fixed?

**Comment by edgr-sanchez** [comment]
So I still get this warning on Safari. Is core going to get updated to avoid this issue? 
![screen shot 2015-10-15 at 10 57 35 am](https://cloud.githubusercontent.com/assets/12093243/10519502/9ba2e9ca-732b-11e5-8511-094470cc258b.png)

**Comment by antoinemenini** [comment]
Same problem for me. Does anyone have a fix?

**Comment by MiguelMike** [comment]
Here's an example that of how it should look like to prevent the errors`filter: ~"progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)"`;

**Comment by mfc-julius** [comment]
@MiguelMike, why don't you test it on browsers (IE especially) and create a pull request?

**Comment by tagliala** [comment]
I need to be 1000% sure that this works on IE8

**Comment by mfc-julius** [comment]
Haven't tested, but from this issue here https://github.com/less/less.js/issues/734 it looks like quotes cannot be used for IE6 and IE7, but for IE8 ms-filter should be used instead.

But obviously this should be tested on the actual browser.

**Comment by tagliala** [comment]
Sorry, I come back on my steps, also because I don't know if Dave will keep supporting IE8 in 5.0.0

> filter: ~"progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)";

This dows not work in IE8

If you do not need IE8 support, please consider a custom build, you just need to override mixins.less

```less
---
---
// Mixins
// --------------------------

.fa-icon() {
{% include code/core.less %}
}

.fa-icon-rotate(@degrees, @rotation) {
  -webkit-transform: rotate(@degrees);
      -ms-transform: rotate(@degrees);
          transform: rotate(@degrees);
}

.fa-icon-flip(@horiz, @vert, @rotation) {
  -webkit-transform: scale(@horiz, @vert);
      -ms-transform: scale(@horiz, @vert);
          transform: scale(@horiz, @vert);
}
```

Closing here
