### ISSUE TITLE
Compatibility Error with Bootstrap 2.1.1

### ISSUE THREAD

**Issue by lanort** [FortAwesome/Font-Awesome#509]
As **Twitter Bootstrap 2.1.1** has the following css code for icons, the font-awesome icons are displayed with wrong dimensions and an unwanted background:

``` css
[class^="icon-"],
[class*=" icon-"] {
  display: inline-block;
  width: 14px;
  height: 14px;
  margin-top: 1px;
  *margin-right: .3em;
  line-height: 14px;
  vertical-align: text-top;
  background-image: url("../img/glyphicons-halflings.png");
  background-position: 14px 14px;
  background-repeat: no-repeat;
}
```

The following "reset" worked for me:

``` css
[class^="icon-"], [class*=" icon-"] {
  background-image:none;
  height:auto;
  line-height:normal;
  margin-top:0;
  vertical-align:baseline;
  width:auto;
}
```
