### ISSUE TITLE
Icon request: fa-artstation and fa-artstation-square

### ISSUE THREAD

**Issue by elantzb** [FortAwesome/Font-Awesome#5354]
I've seen people using Font Awesome for their social networking icons, but they all have to hack in their own icons for Artstation.

The website is here:
http://www.artstation.com/

The basic icon is here:
![image](https://cloud.githubusercontent.com/assets/4442027/5657112/c7801254-969d-11e4-81f9-f5bc43fced35.png)

The square icon is here:
![image](https://cloud.githubusercontent.com/assets/4442027/5657115/d795b02c-969d-11e4-9249-8db83146386a.png)

Thanks much!

**Comment by miskopo** [comment]
I would like to have this icon too, please

**Comment by Fnitrox** [comment]
+1 for this one

**Comment by enzoz** [comment]
Would be awesome to have this icon on font-awesome :+1:

**Comment by ianchase09** [comment]
has there been any success with this ? def. want this

**Comment by krystalcampioni** [comment]
+1

**Comment by illustribe** [comment]
+1! :+1:

**Comment by Sythenz** [comment]
+1!

**Comment by saphiresouldier** [comment]
big +1 from me, Artstation is getting more important as an portfolio site for artists everyday and it would be awesome to have the icon included!

**Comment by jbltx** [comment]
+1

**Comment by redoper** [comment]
+1

**Comment by jbltx** [comment]
For people who can't wait, you can find m'y custom font which use artstation and Polycount icons at my website http://www.mickael-b.com

**Comment by SirMoptop** [comment]
+1

**Comment by nervous-entity** [comment]
+1

**Comment by JFDesigner** [comment]
:+1:

**Comment by leonardteo** [comment]
Hi all,

The official icon vector files are available here:
https://www.artstation.com/about/logo

Leo

**Comment by l0stiwisd0m** [comment]
+1

**Comment by serhiikorol** [comment]
+1

**Comment by gvalmon** [comment]
+1

**Comment by ondrejholan** [comment]
+1

**Comment by TylerSangster** [comment]
+1

**Comment by mcwright** [comment]
+1

**Comment by jdugarte** [comment]
+1

**Comment by ntzog** [comment]
+1

**Comment by sangster** [comment]
+1

**Comment by djonatanb** [comment]
+1

**Comment by dansolo** [comment]
+!

**Comment by clarencemartens** [comment]
+1

**Comment by xsynthz** [comment]
+1

**Comment by moth3r** [comment]
+1

**Comment by Sullum97** [comment]
+1

**Comment by ajabotomey** [comment]
+1

**Comment by opico** [comment]
+1

**Comment by kevin1153** [comment]
+1

**Comment by Nazarsokol** [comment]
+1

**Comment by jbltx** [comment]
Some people asked me how to use my custom icons so while we are waiting for this in FontAwesome, here's mine.

1 - Download these files : 
http://www.mickael-b.com/assets/fonts/cg-icons.svg
http://www.mickael-b.com/assets/fonts/cg-icons.eot
http://www.mickael-b.com/assets/fonts/cg-icons.ttf
http://www.mickael-b.com/assets/fonts/cg-icons.woff

2 - Put these files in `/assets/fonts/` for example (like my website).

3 - Add this line in your main `.css` file : 

```css
@font-face{
  font-family:cg-icons;
  src:url(/assets/fonts/cg-icons.eot?z5qas7);
  src:url(/assets/fonts/cg-icons.eot?z5qas7#iefix) format('embedded-opentype'),url(/assets/fonts/cg-icons.ttf?z5qas7) format('truetype'),url(/assets/fonts/cg-icons.woff?z5qas7) format('woff'),url(/assets/fonts/cg-icons.svg?z5qas7#cg-icons) format('svg');
  font-weight:400;
  font-style:normal;
}
i.cg{
  font-family:cg-icons!important;
  speak:none;
  font-style:normal;
  font-weight:400;
  font-variant:normal;
  text-transform:none;
  line-height:1;
  -webkit-font-smoothing:antialiased;
  -moz-osx-font-smoothing:grayscale;
}
.cg-artstation:before{
  content:"\e900";
}
.cg-polycount:before{
  content:"\e901";
}
```

4 - Use artstation and polycount icons using `<i class="cg cg-artstation">` and `<i class="cg cg-polycount">`.
