### ISSUE TITLE
Icon Request: fa-empty-set

### ISSUE THREAD

**Issue by xavhan** [FortAwesome/Font-Awesome#5852]
To illustrate the emptiness or the lack of something. 
The mathematical symbol is ∅ (Unicode U+2205) but an icon would be nice ;)

**Comment by tagliala** [comment]
Please keep in mind this workaround:

```css
.fa-empty-set:before {
  content: '∅';
}
```
