### ISSUE TITLE
translate(0, 0) kills z-index

### ISSUE THREAD

**Issue by mentor2k1** [FortAwesome/Font-Awesome#6023]
The facebook icon should be lay under the red div:

http://jsfiddle.net/ovab9gL5/8/

there is an thread on stackoverflow: http://stackoverflow.com/questions/5472802/css-z-index-lost-after-webkit-transform-translate3d , but this doesn´t solve the problem

**Comment by davegandy** [comment]
This is interesting. The `translate(0,0)` helps out with Firefox rendering, but it's not so important if it's breaking z-index.

@tagliala What do you think here?

**Comment by tagliala** [comment]
I would remove that rule and preserve z-index

**Comment by herrquark** [comment]
```css
@-moz-document url-prefix() { 
  .@{fa-css-prefix} {
    transform: translate(0, 0); // ensures no half-pixel rendering in firefox
  }
}
```
