### ISSUE TITLE
Mixin suggestion

### ISSUE THREAD

**Issue by rmoorman** [FortAwesome/Font-Awesome#6146]
Hello there,

I am using a couple of self-made (LESS) mixins for a little while now to apply font-awesome icons to elements. 

``` less
.fa-icon-content(@icon) {
  .fa-icon();
  content: @icon;
}
.fa-icon-content(@icon, @rules) {
  .fa-icon-content(@icon);
  @rules();
}
.fa-icon-before(@icon) {
  &:before {
    .fa-icon-content(@icon);
  }
}
.fa-icon-before(@icon, @rules) {
  &:before {
    .fa-icon-content(@icon, @rules);
  }
}
.fa-icon-after(@icon) {
  &:after {
    .fa-icon-content(@icon);
  }
}
.fa-icon-after(@icon, @rules) {
  &:after {
    .fa-icon-content(@icon, @rules);
  }
}
```

They can be used something like this:

``` less
.sorted-table th.sort {
  .fa-icon-after(@fa-var-sort, {
    margin-left: 7px;
  });
}
.fancylink {
  .fa-icon-before(@fa-var-rocket);
}
.some-thing-which-already-has-some-after-style {
  &:after {
    .fa-icon-content(@fa-var-bus);
  }
}
```

As far as compatibility is concerned, the mixins use at least one feature which appeared in LESS version 1.7 of less (2014-02-27), namely rulesets.
Porting this to SCSS code shouldn't be too hard either I suppose using `@content`.

Even though I already saw issues #5918 and #2695 which might tangentially related I would like to know if you think that something like those would be a good addition to the current font-awesome library.

Best regards,
Rico Moorman

edit: wording and add note about SCSS
