### ISSUE TITLE
make line-height configurable

### ISSUE THREAD

**Issue by lifeiscontent** [FortAwesome/Font-Awesome#6249]
in `_core.scss`

I've modified this in my own codebase to support my vertical code base's line-height.

this is necessary so the icons sit correctly in vertical alignment

I suggest a `$fa-line-height-base` variable. I can create a pull-request if you want 

``` scss
.#{$fa-css-prefix} {
  display: inline-block;
 // the line below is modified
  font: normal normal normal #{$fa-font-size-base}/#{$fa-line-height-base} FontAwesome; // shortening font declaration
  font-size: inherit; // can't have font-size inherit on line above, so need to override
  text-rendering: auto; // optimizelegibility throws things off #1094
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0); // ensures no half-pixel rendering in firefox

}
```
