### ISSUE TITLE
ISSUE WITH BOOTSTRAP: icons look shifted down in .nav and .btn

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#635]
I found that icons in `.btn` and `.nav` dropdowns are shifted down (by 1 or more pixels depending on size of icon):

http://jsfiddle.net/9mBz5/7/

My workaround is:

``` css
.btn [class^="icon-"],
.nav [class^="icon-"],
.btn [class*=" icon-"],
.nav [class*=" icon-"] {
  line-height: 0.7em;
}
```

I don't know if there are unwanted side effects, so I can't confirm this as a solution and I didn't opened a pull request.

The previous `line-height` value was `.6em`. The comment says: `/* keeps button heights with and without icons the same */`, so I also added in the fiddle buttons without icon. The height is the same (chrome / firefox / safari on osx)

PS: Some icons (like `icon-cog` and `icon-comment`) look "shifted down" in any case

_edit: `0.7em`, `1em` caused un issue on multiline buttons_
