### ISSUE TITLE
Icon Request: icon-cad

### ISSUE THREAD

**Issue by gburton** [FortAwesome/Font-Awesome#6395]
Canadian $ Sign, exact same as the US $ sign.

cad is the ISO 4217 code for the Canadian Dollar.

Thanks

**Comment by greasemonkey2** [comment]
+1....

**Comment by ArtcoInc** [comment]
+1

**Comment by tagliala** [comment]
Sorry, maybe I didn't get this request...

If they are the same symbol, please use `fa-usd` or customize fontawesome to provide an alias

**Comment by tagliala** [comment]
I'm asking to customize because if we add an alias for CAD then we "should" add an alias for AUD and other countries using the $ symbol. That will unnecessarily pollute the css

**Comment by gburton** [comment]
@tagliala - The currency codes are from the database, so it would be a lot of unnecessary logic to try to programatically use usd for cad, aud, nzd, hkd, ars, mxn.  I understand the reluctance to add in the extra alias's to the fontawesome .css

For our needs we can get around it by customizing our "user" .css appropriately; 

````css
.fa-cad:before, .fa-aud:before, .fa-nzd:before, .fa-hkd:before, .fa-ars:before, .fa-mxn:before {
  content: "\f155";
}
````

Thank You for your idea.
