### ISSUE TITLE
Icon request: icon-print-preview

### ISSUE THREAD

**Issue by themiacat** [FortAwesome/Font-Awesome#640]
One for print preview, another for previewing a electronic draft of something that usually does not get printed onto a paper. 

Love Font Awesome.

**Comment by stepev** [comment]
:+1:

**Comment by jhubert** [comment]
:+1:

**Comment by lorencs** [comment]
+1

**Comment by hybopressthemes** [comment]
+1

**Comment by LuisCDias** [comment]
+1

**Comment by Psychokrameur** [comment]
+1

**Comment by Slayer95** [comment]
+1

**Comment by robbytaylor** [comment]
+1 for a preview icon

**Comment by rmies** [comment]
+1

**Comment by mansimransingh** [comment]
+1

**Comment by jkarr** [comment]
+1

**Comment by enkodellc** [comment]
+1

**Comment by MrLonely14** [comment]
+1

**Comment by Marchrius** [comment]
+1 for request and +1 @enkodellc for hack!

**Comment by zendre4** [comment]
+1

**Comment by balasankarc** [comment]
@davegandy  Hi, just a reminder about this issue. Any idea when this will get implemented?

**Comment by Sayant** [comment]
+1 - This is almost three years old now...

**Comment by irman** [comment]
+1

**Comment by zackirby** [comment]
+1
Seems like a pretty basic web application icon. I agree with @Sayant's example.

**Comment by marcintabaka** [comment]
+1

**Comment by jacobherrera** [comment]
+1

**Comment by behramcelen** [comment]
:+1:

**Comment by pitus** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by kiranaghor** [comment]
+1

**Comment by adil9** [comment]
+1

**Comment by AlexLomm** [comment]
+1

**Comment by hackerkid** [comment]
+1

**Comment by myleshk** [comment]
+1

**Comment by lrasmus** [comment]
+1

**Comment by vascop** [comment]
+1

**Comment by kirlisakal** [comment]
+1

**Comment by segreyg** [comment]
+1

**Comment by volodymyrbalytskyy** [comment]
+1

**Comment by giriv** [comment]
+1

**Comment by CaitlinMurphy** [comment]
+1

**Comment by ybozhko** [comment]
+1

**Comment by KazakovVS** [comment]
+1

**Comment by hicklin-james** [comment]
+1

**Comment by darrell-aevum** [comment]
Almost 5 years later, apparently +1 doesn't mean anything.

**Comment by adil9** [comment]
@dareel-aevum exactly, I just keep getting notifications of all these +1 for apparent no reason.

**Comment by ColdHeat** [comment]
I'm amazed that the open source community hasn't simply combined `fa-search` and `fa-file-o` into one icon. This is going on 5 years old.

**Comment by mervinva** [comment]
+1

**Comment by Roy-Orbison** [comment]
A cheaper workaround that doesn't need extra markup:

```
.fa-preview:before {
    content: "\f016";
}
.fa-preview:after {
    content: "\f002";
    display: inline-block;
    font-size: 65%;
    margin-left: -22%;
}
```

Renders as 
![image](https://user-images.githubusercontent.com/28617290/36234951-cef0a3b8-123d-11e8-972a-4f5a592edecf.png)

**Comment by sensibleworld** [comment]
We added a new `print-search` icon to the latest Font Awesome Release: https://fontawesome.com/icons/print-search?style=solid

I'll keep this issue open until we get the `file-search` icon added.

**Comment by TimShilov** [comment]
And here's my workaround. Maybe someone will like it.
CSS:
```css
.fa-file-preview {
    position: relative;
}

.fa-file-preview:before {
    content: '\f016';
}

.fa-file-preview:after {
    content: '\f002';
    font-size: 0.6em;
    position: absolute;
    top: 0.5em;
    right: -0.1em;
    text-shadow: 1px 0 0 #fff, -1px 0 0 #fff, 0 1px 0 #fff, 0 -1px 0 #fff,
        0.5px 0.5px #fff, -0.5px -0.5px 0 #fff, 0.5px -0.5px 0 #fff,
        -0.5px 0.5px 0 #fff;
}
```

HTML:
```html
<i class="fa fa-file-preview"></i>
```

Renders as:
<img width="200" alt="SharedScreenshot jpg" src="https://user-images.githubusercontent.com/20239045/54070263-d8a46900-426e-11e9-942b-7364458d7a2e.png">
