### ISSUE TITLE
Icon Request: fa-new

### ISSUE THREAD

**Issue by thschwz** [FortAwesome/Font-Awesome#6428]
I am looking for a icon which can be used to label something that is new. 
Uses cases:
- Label new products in webshops
- Label messages which are new

Representation, examples:
- text: "NEW"
- Star icon with letter "N"
- Just the letter "N"
- a tag icon with text "New"

**Comment by tagliala** [comment]
Dup of #1331, please +1 that request

If you need an N, then go for plain css:

```css
.fa-new:before {
  font-family: YourMainFontFamily;
  content: 'N';
}
```
