### ISSUE TITLE
W3 Jigsaw fails to validate fontawesome.min.css

### ISSUE THREAD

**Issue by bitzl** [FortAwesome/Font-Awesome#6489]
fontawesome.min.css fails validation in several points:

http://jigsaw.w3.org/css-validator/validator?uri=http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css&warning=0&profile=css3

While some issues address special browser-specific stuff like "@-webkit-keyframes", there are also issues regarding missing semicolons and parse errors.

**Comment by tagliala** [comment]
Sorry, we need to support some browsers that needs custom prefixes and non-standard properties.

If you are not interested in those browser, please consider a custom build of fontawesome

Hope it helps, closing here

**Comment by bitzl** [comment]
Wow, that was fast. But I did *not* complain on custom prefixes and non-standard properties. These are pretty ok if they help to support more browsers.

My point are the "missing semicolons and parse errors" as reported by Jigsaw. If you are interested in this issue, I'd be willing to help.

**Comment by tagliala** [comment]
Unfortunately they are a consequence of the `filter:` property

Try to validate via direct input:
```css
.fa-rotate-90 {
  filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1);
  -webkit-transform: rotate(90deg);
  -ms-transform: rotate(90deg);
  transform: rotate(90deg);
}
```

and then:
```css
.fa-rotate-90 {
  -webkit-transform: rotate(90deg);
  -ms-transform: rotate(90deg);
  transform: rotate(90deg);
}
```
