### ISSUE TITLE
Icons not showing when using Gem

### ISSUE THREAD

**Issue by rydigital** [FortAwesome/Font-Awesome#6773]
Using Font-awesome using the ruby gem (ruby-2.2.2, font-awesome-sass-4.3.2). The font icons look fine locally, but are broken when viewed remotely or when deployed on a server.

I have followed the instructions [laid out here](https://github.com/FortAwesome/font-awesome-sass) but when I look at my compiled CSS the expected unicode numbers have been replaced by boxes:

```CSS
.fa-glass:before {
  content: "";
}
```

instead of

```CSS
.fa-glass:before {
  content: "\f000";
}
```

I have already tried including `@charset "UTF-8";` at the top of my SASS file which imports font-awesome.
