### ISSUE TITLE
Spin in Reverse Direction

### ISSUE THREAD

**Issue by agrobbin** [FortAwesome/Font-Awesome#688]
It'd be great if there was a class you could attach to an icon-\* to have it spin in the reverse direction. It's easily doable by just adding the 'reverse' keyword to the animation, but it'd be great to have a class like icon-spin-reverse.

``` css
.icon-spin-reverse {
  -moz-animation: spin 2s infinite linear reverse;
  -o-animation: spin 2s infinite linear reverse;
  -webkit-animation: spin 2s infinite linear reverse;
  animation: spin 2s infinite linear reverse;
}
```

Or a chainable class:

``` css
.icon-spin.icon-spin-reverse {
  -moz-animation-direction: reverse;
  -o-animation-direction: reverse;
  -webkit-animation-direction: reverse;
  animation-direction: reverse;
}
```

`reverse` was added to the CSS3 spec relatively recently, and only Firefox 16+ and Chrome 19+ support it. Alternatively, it could be done by just inverting the spin keyframes for a spin-reverse class.

**Comment by tagliala** [comment]
do you know browser support of `reverse`?

I'm concerned it is not enough and we have to duplicate the whole animation

**Comment by gangaec** [comment]
+1

**Comment by shivenigma** [comment]
+1

**Comment by neozenith** [comment]
:+1:

**Comment by jamland** [comment]
+1

**Comment by merterhk** [comment]
Here is another code. Based on fa-spin class. Just add your css file.

```
.fa-spin-reverse {
  -webkit-animation: fa-spin-reverse 2s infinite linear;
  animation: fa-spin-reverse 2s infinite linear;
}
@-webkit-keyframes fa-spin-reverse {
  100% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  0% {
    -webkit-transform: rotate(359deg);
    transform: rotate(359deg);
  }
}
@keyframes fa-spin-reverse {
  100% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  0% {
    -webkit-transform: rotate(359deg);
    transform: rotate(359deg);
  }
}

```

to use:

```
<i class="fa fa-spin-reverse fa-cog"></i>
```

**Comment by smithandre** [comment]
+1

**Comment by CrandellWS** [comment]
+1

**Comment by minderov** [comment]
+1

**Comment by yigit-darcin** [comment]
+1

**Comment by phlegx** [comment]
+1

**Comment by shefik** [comment]
+1

**Comment by cooervo** [comment]
+1

**Comment by tomsommer** [comment]
+1

**Comment by blitzmann** [comment]
+1

**Comment by tavuntu** [comment]
+1

**Comment by BlueCoder77** [comment]
+1

**Comment by michaeldevenney** [comment]
+1

**Comment by colleen-smith-levelsbeyond** [comment]
+1

**Comment by pkmccaffrey** [comment]
+1

**Comment by tagliala** [comment]
Almost a decade after... `spin-reverse` is available in FA6!

https://jsfiddle.net/tagliala/0adgjefp/7/

Docs: https://fontawesome.com/v6.0/docs/web/style/animate

`spin-reverse` adds a simple CSS rule to reverse the animation, so it works with all compatible animations (like `fa-pulse`)

FA5 users can keep using custom css and add this rule:

```css
.fa-spin-reverse {
    --fa-animation-direction: reverse;
}
```

Browser compatibility at the moment I'm writing this comment: https://caniuse.com/mdn-css_properties_animation-direction_reverse

For older browser support, please take a look at the above comments
