### ISSUE TITLE
Doesn't work with CSS attr()

### ISSUE THREAD

**Issue by jasonkuhrt** [FortAwesome/Font-Awesome#808]
```
<foo ... checkmark="\f00d" ...>
```

```
...
foo:before {
  content: attr(checkmark);
}
...
```

In the browser we just see: `\f00c`, not an icon.

**Comment by Shaker-Hamdi** [comment]
I'm having the exact same issue, I'm using React, and I want to dynamically render a FontAwesome icon that comes from the API as a string "\f4d3", however, using it like this doesn't work ...
`<i className="f-icon" data-icon="\f4d3"></i>`

It doesn't render the icon in the browser, just the Unicode.

**Comment by isneace** [comment]
Just want to jump in here. This DOES work. You have to use a different encoding for the unicode character when passing through an attr. Rather than using the `\` you have to use `&#x;`. Doing this, in combination of linking your webfonts folder (found in node_modules) you can pass an icon:

```tsx
          <button className="button" data-left-icon="&#xf061;">
            Button
          </button>
```

```css
.button::before {
  font-family: 'Font Awesome 6 Free';
  font-style: normal;
  content: attr(data-left-icon);
  display: inline-block;
  font-weight: 900;
  vertical-align: bottom;
  @apply mr-2;
}
```
