### ISSUE TITLE
abc... and 123...

### ISSUE THREAD

**Issue by fatmirmorina** [FortAwesome/Font-Awesome#8115]
I want have icons about the abc ... z and the numbers 0,1,2,3,4,5,6,7,8,9

**Comment by tagliala** [comment]
Sorry, I'm going to close this one

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please consider custom css,

```css
.fa-alphabet-a:before {
  // you may need other rules to fit your webfont
  content: 'a';
}
```
