### ISSUE TITLE
Icon Request: icon-grip (Vertical drag & drop)

### ISSUE THREAD

**Issue by wwwlicious** [FortAwesome/Font-Awesome#816]
Typically a grip is represented by some dots, it would be great to have an icon like this for denoting draggable elements on a UI.

**Comment by jasonhansel** [comment]
+1

**Comment by jerefrer** [comment]
+1

**Comment by yaru22** [comment]
+1

**Comment by tusbar** [comment]
:+1:

**Comment by stuartlamour** [comment]
+1

**Comment by flashadvocate** [comment]
Can't believe this hasn't been added yet :(

**Comment by wwwlicious** [comment]
I agree, thought this was a reasonable request. The +1's seem to suggest there is a demand for it.

**Comment by doot0** [comment]
+1

**Comment by rcanand** [comment]
+1

**Comment by ckpicker** [comment]
+1

**Comment by thisispiers** [comment]
+1

**Comment by flashadvocate** [comment]
@ArthurClemens thanks for that alternative. Put it to good use. :)

**Comment by DKhalil** [comment]
+1

**Comment by johnjcorcoran** [comment]
+1

**Comment by mrtoddandrews** [comment]
+10

**Comment by georgeportillo** [comment]
+1

**Comment by hughes** [comment]
This seems pretty essential!

**Comment by hughes** [comment]
Two side-by-side ellipsis-v icons can achieve the same effect.

**Comment by jerefrer** [comment]
@hughes Nice trick, thanks :)

**Comment by yagobski** [comment]
+1

**Comment by abanctelchevrel** [comment]
Solution using ellipsis-v icons : 

```css
/* \f142 is ellipsis-v */
/* \202F is thin unbreakable space */
.fa.fa-grip:before {
    content: "\f142 \202F \f142 \202F \f142";
}
.fa.fa-grip-large:before {
    content: "\f142 \202F \f142 \202F \f142 \202F \f142 \202F \f142 \202F \f142 \202F \f142";
}
```


```html
  fa-grip-large : <i class="fa fa-grip-large fa-rotate-90"></i>
  <br>
  <br>
  <br>
  fa-grip <i class="fa fa-grip"></i>
```
Result : 
![fa-grip](http://i.imgur.com/3OqmPh9.png)
