### ISSUE TITLE
More rotate options  (fa-rotate-*)

### ISSUE THREAD

**Issue by benalex94** [FortAwesome/Font-Awesome#8515]
The project I am currently working on has need for (currently custom) rotated icons.

We need increments of 45 degrees rather than 90 as is currently available 

Thank you

**Comment by viion** [comment]
I wouldn't personally see the need for smaller increments because some other use-case could always do even smaller, then it's like why not just add full 360 class case? then the css becomes huge. 

I think smaller increments should be up to the user as it is easily done:

```css
.fa-rotate-45 {
    transform: rotate(45deg);
}
```

As a SCSS loop

```scss
$max: 360;
$step: 45;
@for $i from 1 through ceil($max/$step) { 
    $value: ($i - 1)*$step + 45; 
    .fa-rotate-#{$value} { 
        transform: rotate($value+0deg);
    } 
}
```

Generates:

```css
.fa-rotate-45 {
  transform: rotate(45deg);
}

.fa-rotate-90 {
  transform: rotate(90deg);
}

.fa-rotate-135 {
  transform: rotate(135deg);
}

.fa-rotate-180 {
  transform: rotate(180deg);
}

.fa-rotate-225 {
  transform: rotate(225deg);
}

.fa-rotate-270 {
  transform: rotate(270deg);
}

.fa-rotate-315 {
  transform: rotate(315deg);
}

.fa-rotate-360 {
  transform: rotate(360deg);
}
```
