### ISSUE TITLE
Add class for creating smaller icons called fa-sm

### ISSUE THREAD

**Issue by slauyama** [FortAwesome/Font-Awesome#8647]
I was wondering if it might be a good idea to have a class called `fa-sm` for smaller sized icons. The css would be similar to `fa-lg` and would make the font 33% smaller than the normal size (`font-size: .666666em;`) It might also contain some styles for `line-height` and `vertical-align` (I was not sure what the effects of these styles were so I do not know what the values should be). This would be useful as a standard for smaller sized icons and I think would be a nice feature.

**Comment by cherrador** [comment]
Smaller fonts do not behave properly on some browsers after they are below the 5px and they do not scale properly according the the rest of the fonts. Saying that, I have been on the need to create icons that represent bullets, using px, em, ex or % do not work all the time. Better I used scale that works all the time. I customized my CSS to include this rule:
```css
.fa-sm{
    -webkit-transform: scale(0.5,0.5);
    -ms-transform: scale(0.5,0.5);
    transform: scale(0.5,0.5);
    vertical-align: middle;
}
```
My 3 cents... However I wish should be include on the main project CSS to avoid patching.
