### ISSUE TITLE
Icon Request: fa-futbol

### ISSUE THREAD

**Issue by ab-os** [FortAwesome/Font-Awesome#8902]
I would really like to see a fa-futbol (so the inverse of already existing fa-futbol-o).

Context: I've currently got the futbol (fa-futbol-o) icon in white color on a dark background and now the pentagonal spots, which are usually black on a futbol, are white. An fa-futbol would look better here.

Thank you very much and hopefully I'll see the fa-futbol coming with some update in the future.

**Comment by ryankane** [comment]
You can [stack icons][1] to solve your issue.

![fa-futbol-o Inverted][2]

```html
<span class="fa-stack fa-lg">
  <i class="fa fa-circle fa-stack-1x color-white"></i>
  <i class="fa fa-circle fa-stack-1x color-black"></i>
  <i class="fa fa-futbol-o fa-stack-1x"></i>
</span>
```

```css
body { background: #000000; }
.fa-lg { font-size: 10em; }

.fa-stack .color-white {
  color: #FFFFFF;
  font-size: 1.25em;
}

.fa-stack .color-black {
  color: #FFFFFF;
}
```

  [1]: https://jsfiddle.net/n7g6b1e7/
  [2]: http://i.imgur.com/46YXSW8.png

**Comment by jodyberna1** [comment]
Yeah that kinda solves it. But still isn't the same as a the futbol icon would be. I guess this would come the closest:
https://jsfiddle.net/n7g6b1e7/2/
![image](https://cloud.githubusercontent.com/assets/18310049/14330818/9df06eaa-fc42-11e5-99cf-924dc02142ad.png)
But it needs a stack of 4 icons, 17 lines of CSS code and it isn't flexible for changing backgrounds. The beauty of Font Awesome is its elegance and that's missing in this solution I think. I can image that this stack also could mess up the fixed width (fa-fw) option.

So my request for fa-futbol remains.

**Comment by ryankane** [comment]
By combing JavaScript and SASS, you could do it in [one line][1]. :smile: 

###### HTML

```html
<i class="fa fa-futbol fa-lg"></i>
```

###### JavaScript (jQuery)

```javascript
$(function() {
	var $el = $('.fa-futbol');
  $el.replaceWith([
  	'<span class="fa-stack ' + $el.get(0).className + '">',
    '  <i class="fa fa-circle fa-stack-1x fill"></i>',
    '  <i class="fa fa-futbol-o fa-stack-1x"></i>',
    '  <i class="fa fa-circle-thin fa-stack-1x inner"></i>',
    '  <i class="fa fa-circle-thin fa-stack-1x outer"></i>',
    '</span>'
  ].join(''));
});
```

###### SCSS

```scss
$bg = #7F0000; $fg = #FFFFFF;

body   { background: $bg }

@mixin futbol-inverted($fgColor, $bgColor) {
  .fill                 { color: $fgColor; }
  .fa-futbol-o          { color: $bgColor; }
  .fa-circle-thin.inner { color: $fgColor; font-size: 1.18em; }
  .fa-circle-thin.outer { color: $bgColor; font-size: 1.25em; } 
}

.fa-stack.fa-lg { @include futbol-inverted($fg, $bg); font-size: 10em; }
```

  [1]: https://jsfiddle.net/0nh6zbf4/
