### ISSUE TITLE
Problem using font-awesome within less - there is no icon mixin.

### ISSUE THREAD

**Issue by felipecrp** [FortAwesome/Font-Awesome#9097]
I made a less file with the following content:

``` less
@import 'font-awesome/less/font-awesome.less';
@import 'bootstrap/less/bootstrap.less';

button.open {
    .btn;
    .btn-default;

    i, span {
        .fa;
        .fa-lg;
        .fa-folder-open;
    }
}
```

But got this error:

``` bash
Potentially unhandled rejection [2] .fa-folder-open is undefined
```

It happens with any icon, because apparently there aren´t any mixin for icons.

The solution is change the icons.less content from:

``` less
.@{fa-css-prefix}-folder-open:before { content: @fa-var-folder-open; }
```

to

``` less
.@{fa-css-prefix}-folder-open { &:before { content: @fa-var-folder-open; } }
```

What do you think about this solution? Can you make a fix?

**Comment by felipecrp** [comment]
Possible solution. I will test before the pull request.

https://github.com/felipecrp/Font-Awesome/commit/f17ed432b52b246911758ee0f8e060d6234cd02f

**Comment by tagliala** [comment]
@felipecrp thanks for providing a workaround.

Unfortunately that solution could not be merged, because it may represent a breaking change.

It is already done in the 5.0.0-wip branch but since FA 5.0.0 should keep backward compatibility, maybe that change could be reverted.

Please use something like this

```less
button.open {
    .btn;
    .btn-default;

    i, span {
        .fa;
        .fa-lg;
        &::before { content: @fa-var-folder-open; }
    }
}
```

or a custom mixin like

```css
.fa-before-content(@var) {
  content: @var;
}

button.open {
    .btn;
    .btn-default;

    i, span {
        .fa;
        .fa-lg;
        .fa-before-content(@fa-var-folder-open);
    }
}
```

Ref: #4556
