### ISSUE TITLE
Icon Request: Hexo, Hugo and Jekyll

### ISSUE THREAD

**Issue by fusion809** [FortAwesome/Font-Awesome#9103]
Hi,

I'd like to request icons for the following static site generators:

* Hexo (roughly modelled on [this logo](http://wwwhere.io/img/thumbs/hexo.jpg))
* Hugo (roughly modelled on [this](https://raw.githubusercontent.com/spf13/hugo/master/docs/static/img/hugoSM.png))
* Jekyll (roughly modelled on [this](https://pbs.twimg.com/profile_images/378800000722495387/ad968c1615d956e800fa36494314f48c.jpeg))

I personally want to use these icons on [*The Hornery*](https://fusion809.github.io), my Jekyll-powered GitHub Pages-hosted website and to refer to projects using the respective SSG in the Atom text editor. I have included Font Awesome in my local copy of the Atom text editor using this style sheet and Font-Awesome being cloned to `~/.atom/Font-Awesome`:

```less
@font-face {
  font-family: 'FontAwesome';
  src: url('Font-Awesome/fonts/fontawesome-webfont.eot?v=4.6.1');
  src: url('Font-Awesomefonts/fontawesome-webfont.eot?#iefix&v=4.6.1') format('embedded-opentype'), url('Font-Awesomefonts/fontawesome-webfont.woff2?v=4.6.1') format('woff2'), url('Font-Awesomefonts/fontawesome-webfont.woff?v=4.6.1') format('woff'), url('Font-Awesomefonts/fontawesome-webfont.ttf?v=4.6.1') format('truetype'), url('Font-Awesomefonts/fontawesome-webfont.svg?v=4.6.1#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

and I have already referred to one Font Awesome icon in my `projects.cson` (used by the `projects-manager` Atom package) file, which is (notice the line `icon: "fa fa-linux"`):

```cson
"arch-scripts":
  title: "arch-scripts"
  paths: [
    "/home/fusion809/Shell"
    "/home/fusion809/.bashrc"
    "/home/fusion809/.zshrc"
  ]
"fusion809.github.io":
  title: "fusion809.github.io"
  paths: [
    "/home/fusion809/GitHub/mine/fusion809.github.io"
  ]
  icon: "fa fa-linux"
"hexo-site":
  title: "hexo-site"
  paths: [
    "/home/fusion809/GitHub/mine/hexo-site"
  ]
PKGBUILDs:
  title: "PKGBUILDs"
  paths: [
    "/home/fusion809/GitHub/mine/PKGBUILDs"
  ]
```

Thanks for your time,
Brenton
