### ISSUE TITLE
Placeholders instead of classes

### ISSUE THREAD

**Issue by deioo** [FortAwesome/Font-Awesome#9426]
Would be really useful to create a `$fa-class-prefix: '.' !default;` and use it instead of the default dot in the `_icons.scss` stylesheet, e.g 
```scss
#{$fa-class-prefix}#{$fa-css-prefix}-glass:before { content: $fa-var-glass; }
#{$fa-class-prefix}#{$fa-css-prefix}-music:before { content: $fa-var-music; }
#{$fa-class-prefix}#{$fa-css-prefix}-search:before { content: $fa-var-search; }
```

This way, when using the sass version, it could be used with `@extend %fa-icon-name` _(and  `$fa-class-prefix: '%')_

As a result, all `.fa-` icon classes won't be generated in the compiled / output css _(which rounds up to over 2k lines of code)_. Only the extended ones would.
