### ISSUE TITLE
Icon Request: fa-barcode-search

### ISSUE THREAD

**Issue by douglasdeodato** [FortAwesome/Font-Awesome#9447]
Hello,

Use case: Gps, location, logistics, tracking , Code, magnifier, number,

![tracking_number-128](https://cloud.githubusercontent.com/assets/993318/16265351/bf690e64-3876-11e6-8265-b15e5313aa73.png)

**Comment by tagliala** [comment]
this icon is way too complex to fit in 14px icon size. We already have struggles with the http://fontawesome.io/icon/barcode/ and there is a request to optimize that (#3797)

Renamed to `barcode-search`

Refers to #1181

**Comment by ryankane** [comment]
You can always [stack icons][1].

```html
<span class="fa-stack fa-lg">
  <i class="fa fa-barcode fa-stack-2x"></i>
  <i class="fa fa-search fa-stack-1x"></i>
  <i class="fa bar-text fa-stack-1x">123&nbsp;&nbsp;567</i>
</span>
```

```css
.fa-search {
  font-size: 1.5em;
  line-height: 2.8em;
  text-align: left;
  left: -0.025em;
}

.bar-text {
  font-size: 0.5em;
  line-height: 8.0em;
}
```

  [1]: https://jsfiddle.net/58gfhyhu/
