### ISSUE TITLE
variant: hover rate by less

### ISSUE THREAD

**Issue by EarthDweller** [FortAwesome/Font-Awesome#9538]
``` less
.rating {
    font-family: FontAwesome;
    color: #DDDDDD;

    &:hover {
        span:before {
            content: "\f055";
            color: #28972C;
        }
    }

    span {
        padding-left: 5px;

        &:before {
            content: "\f1db";
        }

        &:hover {
            color: #28972C;
            &:before {
                content: "\f055";
            }
            @max-rate: 5;
            .add-style-for-preceded(@count-after) when (@count-after < @max-rate) {
                & + span {
                    &:before {
                        content: "\f1db";
                    }
                    .add-style-for-preceded(@count-after + 1)
                }
            }
            .add-style-for-preceded(1)
        }
    }
}
```
