### ISSUE TITLE
Icon request: icon-new

### ISSUE THREAD

**Issue by robotwerks** [FortAwesome/Font-Awesome#9690]
This could be used to label new products, content items, etc.

Example: One of our monitor/recorders now allows for Dual 4K recording - I would love to be able to add a little "NEW!" icon next to "Dual 4K" in the features list.

This could also help identify new content in blogs, forums, carts, etc. and could be done programmatically so that the NEW! icon only appears for a set amount of time.

fa-icon-new
![fa-icon-new-solid](https://cloud.githubusercontent.com/assets/18663340/17341168/a49def96-58b0-11e6-8cfe-613e629d9cc6.png)

fa-icon-new-lt
![fa-icon-new-lines](https://cloud.githubusercontent.com/assets/18663340/17341167/a49a0cbe-58b0-11e6-83bb-0eb73d4327a6.png)

**Comment by ryankane** [comment]
You can simply create a `<span>` with text content and a border. https://jsfiddle.net/4oy1o29y/

![new](https://cloud.githubusercontent.com/assets/1094151/17349809/f97822be-58ee-11e6-899f-c51200158b85.png)

## HTML

```html
<span class="logo-stack logo-sm logo-hallow"></span>
<span class="logo-stack logo-md logo-hallow"></span>
<span class="logo-stack logo-lg logo-hallow"></span>
<br />
<span class="logo-stack logo-sm logo-filled"></span>
<span class="logo-stack logo-md logo-filled"></span>
<span class="logo-stack logo-lg logo-filled"></span>
```

## CSS

```css
.logo-sm:before { font-size: 0.8em; }
.logo-sm { margin-top: 1.25em; width: 2.5em; height: 1em; line-height: 0.9em;
  border-radius: 0.2em; -webkit-border-radius: 0.2em; -moz-border-radius: 0.2em; }
.logo-md:before { font-size: 4em; }
.logo-md { margin-top: 2em; width: 12.5em; height: 5em; line-height: 4.5em;
  border-radius: 1em; -webkit-border-radius: 1em; -moz-border-radius: 1em; }
.logo-lg:before { font-size: 8em; }
.logo-lg { margin-top: 4em; width: 25em; height: 10em; line-height: 9em;
  border-radius: 2em; -webkit-border-radius: 2em; -moz-border-radius: 2em; }

.logo-filled {
  color: #FFFFFF;
  background: #000000;
}

.logo-hallow {
  color: #000000;
  border-color: #000000;
  border-style: solid;
}

.logo-stack {
  display: inline-block;
  text-align: center;
  font-family: "Arial Black", "Arial Bold", Gadget, sans-serif;
  font-weight: 100;
          transform: scale(1.0, 1.2); /* W3C */
  -webkit-transform: scale(1.0, 1.2); /* Safari and Chrome */
     -moz-transform: scale(1.0, 1.2); /* Firefox */
      -ms-transform: scale(1.0, 1.2); /* IE 9 */
       -o-transform: scale(1.0, 1.2); /* Opera */
}

.logo-stack:before {
  content: "NEW";
}
```
